force-app/main/default/objects/abd_Census__c/abd_Census__c.object-meta.xml
<CustomObject>
    <description>Global table that contains information regarding City/County.</description>
    <label>Census</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Census</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_Census__c/fields/abd_County__c.field-meta.xml
<CustomField>
    <fullName>abd_County__c</fullName>
    <label>County</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_County_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/abd_Census__c/fields/abd_Population__c.field-meta.xml
<CustomField>
    <fullName>abd_Population__c</fullName>
    <label>Population</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/abd_Census__c/fields/abd_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_End_Date__c</fullName>
    <inlineHelpText>Last day the policy is effective</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Length__c.field-meta.xml
<CustomField>
    <fullName>abd_Length__c</fullName>
    <inlineHelpText>License Duration, 8 month, 12 month, etc.</inlineHelpText>
    <label>Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Local_Authority_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Local_Authority_Type__c</fullName>
    <label>Local Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>City</fullName>
                <default>true</default>
                <label>City</label>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_County__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_County__c</fullName>
    <label>Premises County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adair</fullName>
            </value>
            <value>
                <fullName>Adams</fullName>
            </value>
            <value>
                <fullName>Allamakee</fullName>
            </value>
            <value>
                <fullName>Appanoose</fullName>
            </value>
            <value>
                <fullName>Audubon</fullName>
            </value>
            <value>
                <fullName>Benton</fullName>
            </value>
            <value>
                <fullName>Black Hawk</fullName>
            </value>
            <value>
                <fullName>Boone</fullName>
            </value>
            <value>
                <fullName>Bremer</fullName>
            </value>
            <value>
                <fullName>Buchanan</fullName>
            </value>
            <value>
                <fullName>Buena Vista</fullName>
            </value>
            <value>
                <fullName>Butler</fullName>
            </value>
            <value>
                <fullName>Calhoun</fullName>
            </value>
            <value>
                <fullName>Carroll</fullName>
            </value>
            <value>
                <fullName>Cass</fullName>
            </value>
            <value>
                <fullName>Cedar</fullName>
            </value>
            <value>
                <fullName>Cerro Gordo</fullName>
            </value>
            <value>
                <fullName>Cherokee</fullName>
            </value>
            <value>
                <fullName>Chickasaw</fullName>
            </value>
            <value>
                <fullName>Clarke</fullName>
            </value>
            <value>
                <fullName>Clay</fullName>
            </value>
            <value>
                <fullName>Clayton</fullName>
            </value>
            <value>
                <fullName>Clinton</fullName>
            </value>
            <value>
                <fullName>Crawford</fullName>
            </value>
            <value>
                <fullName>Dallas</fullName>
            </value>
            <value>
                <fullName>Davis</fullName>
            </value>
            <value>
                <fullName>Decatur</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Des Moines</fullName>
            </value>
            <value>
                <fullName>Dickinson</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_State__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_State__c</fullName>
    <label>Premises State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Planning Applications</relationshipLabel>
    <relationshipName>Application2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Active_Status__c.field-meta.xml
<CustomField>
    <fullName>abd_Active_Status__c</fullName>
    <formula>If(AND( abd_Effective_Date__c&lt;=Today(), abd_Effective_End_Date__c  >=Today()),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>License Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Effective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_End_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Length__c.field-meta.xml
<CustomField>
    <fullName>abd_Length__c</fullName>
    <label>Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Local_Authority_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Local_Authority_Type__c</fullName>
    <label>Local Authority Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Premise_City__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_City__c</fullName>
    <label>Premises City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Related Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>License2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Primary_Licensee__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Primary_Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the help text for the Primary Licensee</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>License2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_AdditionalLocation.cls
public with sharing class DX_AdditionalLocation {
    // This routine is used by the premise form and the update premise form	


	static String notAnswered = '--None--';
	// Get the list of values for the picklist field and pass them back to the lightning component.
    // Add the -- not answered-- choice as the first value.  If we move to radial buttons, this can all change.
    @AuraEnabled
    public static map<string,string[]> getPicklistValues(){
		map<string,string[]> pickVals = new map<string,string[]>();
        string[] options = new string[]{};
        Schema.DescribeFieldResult fieldResult = MUSW__Application2__c.abd_Premise_State__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.put('state',options);



        options = new List<String>();
        fieldResult = MUSW__Application2__c.abd_Premise_County__c.getDescribe();
        ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.put('county',options);
        options = new List<String>();
        fieldResult = MUSW__Application2__c.abd_Start_Time__c.getDescribe();
        ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.put('time',options);
        return pickVals;
    }
	//Methods for dx_AdditionalLocation
    @AuraEnabled
    public static MUSW__License2__c getLicense(Id licenseId){
        
        return [Select abd_License_Type__c, MUSW__Primary_Licensee__c, MUSW__Applicant__c, abd_Effective_Date__c,abd_Effective_End_Date__c,
                        abd_Local_Authority_Type__c, abd_Premise_City__c, abd_Premise_County__c,  abd_Length__c, 
        		(Select abd_License_Type__c From Licenses__r where abd_Active_Status__c=true) 
        		From MUSW__License2__c 
        		where id = :licenseId];
    }
	@AuraEnabled
    public static list<abd_Census__c> getPremiseCity(string county){
    	list<abd_Census__c> temp = new list<abd_Census__c>();
    	temp.add(new abd_Census__c(name='--None--'));
       	for(abd_Census__c a:[Select Name,abd_Population__c from abd_Census__c where abd_County__c!=null and abd_County__c includes(:county) and abd_Type__c='City' order by Name]){
       		temp.add(a);	
       	} 
       	return temp;
    }
	@AuraEnabled
    public static string createAddApp(MUSW__Application2__c application, MUSW__License2__c license){
        Savepoint sp = Database.setSavepoint();
        try{
        	Id devRecordTypeId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Additional Locations Application').getRecordTypeId();
            User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
            if(u.ContactId==null){
                return 'The logged in User does not have an Applicant record';
            }
            system.debug(application);
            system.debug(devRecordTypeId);
            system.debug(license);
            
            application.abd_Application_Type__c ='Additional Locations';
            application.recordTypeId=devRecordTypeId;
            application.MUSW__Account__c=license.MUSW__Primary_Licensee__c;  // DRE replaces it.
            application.MUSW__Applicant__c=license.MUSW__Applicant__c;
            application.name='System Number';
            application.MUSW__Status__c='Pending';
            application.abd_Primary_License__c=license.Id;
            application.abd_Portal_Processed__c = true;
			system.debug(application);
            insert application;
            return 'SUCCESS: ' + String.valueOf(application.Id);
        }catch (Exception ex) {
        	system.debug(ex.getMessage());
            Database.rollback(sp);
        	throw new AuraHandledException(ex.getMessage());
        }
    }
    
}