force-app/main/default/objects/BGCK__Checklist_Version__c/BGCK__Checklist_Version__c.object-meta.xml
<CustomObject>
    <label>Checklist Version</label>
    <nameField>
        <displayFormat>CV{000000}</displayFormat>
        <label>Checklist Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Checklist_Version__c/fields/BGCK__Page__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Page</label>
    <referenceTo>BGCK__Page__c</referenceTo>
    <relationshipLabel>Checklist Versions</relationshipLabel>
    <relationshipName>Checklist_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Checklist_Version__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Checklist Versions</relationshipLabel>
    <relationshipName>Checklist_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Page__c/BGCK__Page__c.object-meta.xml
<CustomObject>
    <label>Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Page__c/fields/BGCK__Checklist_Version__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Checklist_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist Version</label>
    <referenceTo>BGCK__Checklist_Version__c</referenceTo>
    <relationshipLabel>Pages</relationshipLabel>
    <relationshipName>Pages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Page__c/fields/BGCK__Order__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BGCK__Page__c/fields/BGCK__Type__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Title</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Sub-Section</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGCK__Page_Question__c/BGCK__Page_Question__c.object-meta.xml
<CustomObject>
    <label>Page Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Page_Question__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGCK__Page_Question__c/fields/BGCK__Order__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Order__c</fullName>
    <defaultValue>1</defaultValue>
    <description>This can not have decimal point,  must be a integer</description>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BGCK__Page_Question__c/fields/BGCK__Page__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Page__c</fullName>
    <label>Page</label>
    <referenceTo>BGCK__Page__c</referenceTo>
    <relationshipLabel>Page Questions</relationshipLabel>
    <relationshipName>Page_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BGCK__Page_Question__c/fields/BGCK__Parent_Page_Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Parent_Page_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Page Question</label>
    <referenceTo>BGCK__Page_Question__c</referenceTo>
    <relationshipLabel>Page Questions</relationshipLabel>
    <relationshipName>Page_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Page_Question__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Page Questions</relationshipLabel>
    <relationshipName>Page_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Page_Question__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGCK__Question__c/BGCK__Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Question__c/fields/BGCK__Checklist_Version__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Checklist_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist Version</label>
    <referenceTo>BGCK__Checklist_Version__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Question__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Question__c/fields/BGCK__Question_Type__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>BGCK__Question_Type__c.BGCK__Checklist_Version__r.BGCK__Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </filterItems>
        <filterItems>
            <field>BGCK__Question_Type__c.BGCK__Checklist_Version__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.BGCK__Checklist_Version__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BGCK__Question_Type__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Question_Type__c/BGCK__Question_Type__c.object-meta.xml
<CustomObject>
    <label>Question Type</label>
    <nameField>
        <label>Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Question_Type__c/fields/BGCK__Checklist_Version__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Checklist_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist Version</label>
    <referenceTo>BGCK__Checklist_Version__c</referenceTo>
    <relationshipLabel>Question Types</relationshipLabel>
    <relationshipName>Question_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Question_Type__c/fields/BGCK__Type__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Radio Button</fullName>
            </value>
            <value>
                <fullName>Checkbox - Horizontal</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Checkbox - Vertical</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Number - Percent</fullName>
            </value>
            <value>
                <fullName>Number - Integer</fullName>
            </value>
            <value>
                <fullName>Number - Currency</fullName>
            </value>
            <value>
                <fullName>Phone Number</fullName>
            </value>
            <value>
                <fullName>Record List</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>Number - Decimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DX_DynamicChecklistQuestions_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class DX_DynamicChecklistQuestions_Test {

    @testSetup 
	static void setup() {
        TestUtils.Create_Citizen_Account();
        TestUtils.SetRoleForCurrentUser();
    }
    
    static testMethod void myUnitTest() {
        
        //THIS WILL MOVE TO A METHOD IN TESTUTILS THEN BE CALLED IN THE SETUP()
        BGCK__Checklist_Version__c ch = new BGCK__Checklist_Version__c();
        insert ch;
        BGCK__Page__c p = new BGCK__Page__c(name='Test Page',BGCK__Order__c=1,BGCK__Checklist_Version__c=ch.Id );
        insert p;
        BGCK__Question_Type__c qt = new BGCK__Question_Type__c(Name = 'Test Type', BGCK__Type__c='Radio Button', BGCK__Checklist_Version__c = ch.Id);
        insert qt;
        BGCK__Question__c q = new BGCK__Question__c(Name = 'Test Question 1', BGCK__Checklist_Version__c = ch.Id, BGCK__Question_Type__c = qt.Id);
        insert q;
        BGCK__Page_Question__c ppq = new BGCK__Page_Question__c(Name = 'Test PQ 1', License_Type__c = 'CP', BGCK__Question__c = q.Id, BGCK__Page__c = p.Id, BGCK__Order__c = 1, Application_Type__c ='New License');
        insert ppq;
        qt = new BGCK__Question_Type__c(Name = 'Test Type', BGCK__Type__c='Text', BGCK__Checklist_Version__c = ch.Id);
        insert qt;
        q = new BGCK__Question__c(Name = 'Test Question 2', BGCK__Checklist_Version__c = ch.Id, BGCK__Question_Type__c = qt.Id);
        insert q;
        BGCK__Page_Question__c pq = new BGCK__Page_Question__c(Name = 'Test PQ 2', License_Type__c = 'CP', BGCK__Question__c = q.Id, BGCK__Parent_Page_Question__c = ppq.Id, BGCK__Page__c = p.Id, BGCK__Order__c = 2, Application_Type__c ='New License');
        insert pq;
        //END OF METHOD
        Account a = TestUtils.Create_Account('Customer', 1)[0];
        Contact c = TestUtils.Create_Contacts(1, a)[0];
        User pu = new User(Id=userInfo.getUserId());
        MUSW__Application2__c app = TestUtils.CreateApplication(pu,c,a,'LE','Class E Liquor License');
        test.startTest();
        DX_DynamicChecklistQuestions.getChecklist('CP','New License',ch.Id,app.Id);
        test.stopTest();
        
    }
}