force-app/main/default/objects/Application_Contact__c/Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>APC-{000000}</displayFormat>
        <label>Application Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Contact__c/fields/abd_EIN__c.field-meta.xml
<CustomField>
    <fullName>abd_EIN__c</fullName>
    <description>Used for State EIN typically on this object, but it could be a Federal EIN as well.</description>
    <label>EIN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_Federal_Gambling_Stamp__c.field-meta.xml
<CustomField>
    <fullName>abd_Federal_Gambling_Stamp__c</fullName>
    <label>Federal Gambling Stamp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_LicenseeBusinessType__c.field-meta.xml
<CustomField>
    <fullName>abd_LicenseeBusinessType__c</fullName>
    <formula>Text(Application__r.MUSW__Account__r.Business_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LicenseeBusinessType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_Primary_Owner__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_State_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>abd_State_of_Incorporation__c</fullName>
    <label>State of Incorporation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>BGCK__Answer__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <label>Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/of_Ownership__c.field-meta.xml
<CustomField>
    <fullName>of_Ownership__c</fullName>
    <label>% of Ownership</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>11</length>
    <maskChar>X</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/U_S_Citizen__c.field-meta.xml
<CustomField>
    <fullName>U_S_Citizen__c</fullName>
    <label>U.S. Citizen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/BGCK__Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Answer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Question__c/BGCK__Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Question__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_Date_of_Current_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date_of_Current_License__c</fullName>
    <label>Start Date of Current License</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_End_Date_of_Current_Lic__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_End_Date_of_Current_Lic__c</fullName>
    <label>Expiration Date of Current License</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_PortalWork_LicenseType__c.field-meta.xml
<CustomField>
    <fullName>abd_PortalWork_LicenseType__c</fullName>
    <description>Temporary field used by the Apex - Lightning transport interface for non-persisted objects</description>
    <label>PortalWork_LicenseType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>DRAM Review</fullName>
            </value>
            <value>
                <fullName>Local Authority Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 1 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 2 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 3 Review</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dx_UpdateOwnershipApplication.cls
public class dx_UpdateOwnershipApplication {
	static String notAnswered = '--None--';
	
     // FOR THE UPDATE OWNERSHIP application
    @AuraEnabled
    public static MUSW__Application2__c createApplicationfromLicense(ID licenseId) {
        try {
            User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
            
            // if this fails (user timed out), then we need to 
            if (u == (User)null || u.ContactId == null) 
            	throw new AuraHandledException ('User does not appear to be logged in anymore');
			Id OwnershipRecordType = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Ownership Update').getRecordTypeId();
            MUSW__Application2__c application;
            //for(MUSW__Application2__c a:[Select Id,abd_Effective_End_Date_of_Current_Lic__c,abd_Effective_Date_of_Current_License__c,abd_Effective_Date__c from MUSW__Application2__c where abd_Primary_License__c=:licenseId 
            //								and RecordTypeId =: OwnershipRecordType and abd_Application_Type__c = 'Ownership Update']){
            //	application = a;	
            //}
            if(application == null){
	            application = DX_Utils.CreateAppFromLicense(licenseId);
	            application.MUSW__Status__c = 'Pending';
	            //application.name='System Number';
	            application.abd_Application_Type__c = 'Ownership Update'; 
				application.RecordTypeId = OwnershipRecordType;            
	            insert application;
				Integer numberofAnswers = DX_Utils.BuildEmptyAnswers(application.id, application.abd_Application_Type__c, application.abd_PortalWork_LicenseType__c);
            }
	        return application;

        }catch (exception ex) {
            System.debug(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
            throw new AuraHandledException(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
        }
    }   

    // Update the record - called from Lightning component.  The lightning component handles the validation now. 
    @AuraEnabled
    public static String UpdateApplication(MUSW__Application2__c application,string ownerString) {
        try{
			list<DX_OwnerList.OwnerInfo> ownerlist = (list<DX_OwnerList.OwnerInfo>) JSON.deserializeStrict(ownerString,list<DX_OwnerList.OwnerInfo>.class);
	        Application_Contact__c[] deletelist = new Application_Contact__c[]{};
	        Application_Contact__c[] updatelist = new Application_Contact__c[]{};
	        BGCK__Answer__c answer = [select Id, Name from BGCK__Answer__c where Application__c =: application.Id and BGCK__Question__r.Name='Owner Details' limit 1];
        	for(DX_OwnerList.OwnerInfo oi:ownerlist){
	        	if(oi.needDelete){
	        		if(oi.owner.Id!=null)
	        			deletelist.add(oi.owner);
	        	}else{
	        		if(oi.owner.U_S_Citizen__c == notAnswered)
	        			oi.owner.U_S_Citizen__c = null;
	        		if (answer != null)
			        	oi.owner.Answer__c = answer.Id;
			        updatelist.add(oi.owner);
	        	}
	        }
	        try{
	        	if(updatelist.size() > 0)
	        		upsert updatelist;
	        	if(deletelist.size() > 0)
	        		delete deletelist;
	        		
	        	answer.Name = string.valueOf([Select Count(Id) from Application_Contact__c where Answer__c=:answer.Id][0].get('expr0'))+' related record(s)';
	        	update answer;
	        
	        }catch(exception ex){
	            throw new AuraHandledException(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
	        }
        	// Set the record Type of the application
            application.MUSW__Status__c = 'In Progress';
            update application;
        }catch(exception ex){
            throw new AuraHandledException(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
        }

        return application.Id;
    }
    
    @AuraEnabled
	public static string[] getPicklistValues(){
		List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Application_Contact__c.State__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        system.debug(options);
        return options;
	}
	
	@AuraEnabled
	public static DX_OwnerList.OwnerInfo[] getOwnerList(Id id){
		DX_OwnerList.OwnerInfo[] ownerlist = new DX_OwnerList.OwnerInfo[]{};
		for(Application_Contact__c o:[Select  Id,Application__c,Business_Name__c,First_Name__c,Last_Name__c,Address__c,
										Address_2__c,City__c,State__c,Zip_Code__c,abd_State_of_Incorporation__c,abd_Primary_Owner__c,Position__c,SSN__c,
										abd_Federal_Gambling_Stamp__c,Date_of_Birth__c,U_S_Citizen__c,of_Ownership__c, abd_LicenseeBusinessType__c, abd_EIN__c
										from Application_Contact__c where Application__c=:id]){
			ownerlist.add(new DX_OwnerList.OwnerInfo(o));	
		}	 
		return ownerlist;
	}
    
    @AuraEnabled
	public static DX_OwnerList.OwnerInfo[] getNewOwners(Id appId,Integer amount){
		DX_OwnerList.OwnerInfo[] ownerlist = new DX_OwnerList.OwnerInfo[]{};

		for(integer i=0;i<amount;i++){
				ownerlist.add(new DX_OwnerList.OwnerInfo(new Application_Contact__c(Application__c = appId ,Business_Name__c='',First_Name__c='',Last_Name__c='',Address__c='',Address_2__c='',City__c='',Zip_Code__c='',
					Position__c='',SSN__c='')));
		}
		return ownerlist;
	}
}