force-app/main/default/objects/Application_Contact__c/Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>APC-{000000}</displayFormat>
        <label>Application Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Contact__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>11</length>
    <maskChar>X</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dx_OwnerAccountSearch.cls
public without sharing class dx_OwnerAccountSearch {
    
    @AuraEnabled
    public static list<Account> getAccounts(string qfs){
        list<Account> la  = new list<Account>();
        map<string,AccountContactRelation> lacr  = new map<string,AccountContactRelation>();
        User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
        system.debug(qfs);
        QueryFields qf = (QueryFields)JSON.deserializeStrict(qfs,QueryFields.class);
        system.debug(qf);
        for(Application_Contact__c ac:[Select Application__r.MUSW__Account__r.Name,Application__r.MUSW__Account__c, SSN__c 
                                       from Application_Contact__c where First_Name__c =:qf.firstname and Last_Name__c=:qf.lastName]){
            System.debug('OAS: ' + ac);
            if (qf.ssn.contains('-')) qf.ssn = qf.ssn.replace('-','');
            System.debug('OAS: ssn fixed' + qf.ssn);
        	if(qf.ssn == ac.SSN__c){
            System.debug('OAS: ssn Match');
                la.add(new Account(Id=ac.Application__r.MUSW__Account__c,Name=ac.Application__r.MUSW__Account__r.Name));
                string key = string.valueOf(ac.Application__r.MUSW__Account__c)+string.valueOf(u.ContactId);
                System.debug('OAS: key ' + key);
                if(u.ContactId!=null && !lacr.containsKey(key)) {
                    System.debug('OAS: ready to put LACR');
                	lacr.put(key,new AccountContactRelation(AccountId=ac.Application__r.MUSW__Account__c,ContactId=u.ContactId));

                }
        	}
        }
        for(AccountContactRelation acr:[Select Id, AccountId,ContactId from AccountContactRelation where ContactId=:u.ContactId]){
            System.debug('OAS ACR: ' + acr);
        	string key = string.valueOf(acr.AccountId)+string.valueOf(acr.ContactId);
        	if(lacr.containskey(key))
        		lacr.put(key,acr);
        }
        if(lacr.size()>0){
        	upsert lacr.values();	
        }
        
        return la;
    }
	
    @AuraEnabled
    public static string updateUser(Id accountId){
        system.debug(accountId);
        User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
        Contact c = new Contact(Id=u.ContactId,AccountId=accountId);
        update c;
        return null;
    }
	
    public class QueryFields{
        
        public QueryFields() {}

        @AuraEnabled
        public string firstName { get;set; }
        
        @AuraEnabled
        public string lastName { get;set; }
        
        @AuraEnabled
        public string ssn { get;set; }
        
    }
}