force-app/main/default/objects/Application_Contact__c/Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>APC-{000000}</displayFormat>
        <label>Application Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Contact__c/fields/abd_LicenseeBusinessType__c.field-meta.xml
<CustomField>
    <fullName>abd_LicenseeBusinessType__c</fullName>
    <formula>Text(Application__r.MUSW__Account__r.Business_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LicenseeBusinessType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_Primary_Owner__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>BGCK__Answer__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <label>Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/of_Ownership__c.field-meta.xml
<CustomField>
    <fullName>of_Ownership__c</fullName>
    <label>% of Ownership</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/BGCK__Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Answer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Question__c/BGCK__Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Question__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_OwnerList.cls
public without sharing class DX_OwnerList {
	
	@AuraEnabled
	public static OwnerInfo[] getOwnerList(Id id){
		OwnerInfo[] ownerlist = new OwnerInfo[]{};
		for(Application_Contact__c o:[Select Id,Application__c,First_Name__c,Last_Name__c,abd_Primary_Owner__c,
										of_Ownership__c, Business_Name__c, abd_LicenseeBusinessType__c
										from Application_Contact__c where Application__c=:id]){
			ownerlist.add(new OwnerInfo(o));	
		}	 
		return ownerlist;
	}
    
    @AuraEnabled
    public static String upRecordApex(string ownerString){
    	list<OwnerInfo> ownerlist = (list<OwnerInfo>) JSON.deserializeStrict(ownerString,list<OwnerInfo>.class);
        Application_Contact__c[] deletelist = new Application_Contact__c[]{};
        Application_Contact__c[] updatelist = new Application_Contact__c[]{};
        Id appId;
        for(OwnerInfo oi:ownerlist){
        	if(appId==null)
        		appId = oi.owner.Application__c;
        	if(oi.needDelete){
        		deletelist.add(oi.owner);
        	}else{
        		updatelist.add(oi.owner);
        	}
        }
        try{
        	if(updatelist.size() > 0)
        		update updatelist;
        	if(deletelist.size() > 0)
        		delete deletelist;
        		
        	BGCK__Answer__c answer = [select Id, Name from BGCK__Answer__c where Application__c =: appId and BGCK__Question__r.Name='Owner Details' limit 1];
        	answer.Name = string.valueOf([Select Count(Id) from Application_Contact__c where Answer__c=:answer.Id][0].get('expr0'))+' related record(s)';
        	update answer;
        
        }catch(exception ex){
            return ex.getMessage();
        }
        
        return 'Update Successful';
    }   
    
    public class OwnerInfo{
    	
    	@AuraEnabled
	    public Application_Contact__c owner{get;set;}
    	@AuraEnabled
	    public boolean needDelete{get;set;}
    	
    	public OwnerInfo(Application_Contact__c ac){
    		this.owner = ac;
    		this.needDelete = false;	
    	}
    }
}