force-app/main/default/objects/abd_License_Types__c/abd_License_Types__c.object-meta.xml
<CustomObject>
    <label>License Type</label>
    <nameField>
        <displayFormat>LT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Types__c/fields/abd_Class__c.field-meta.xml
<CustomField>
    <fullName>abd_Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brewer's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Broker's Permit</fullName>
            </value>
            <value>
                <fullName>Carrier Permit</fullName>
            </value>
            <value>
                <fullName>Charity Beer Wine and Liquor Auction Permit</fullName>
            </value>
            <value>
                <fullName>Class A Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Beer License</fullName>
            </value>
            <value>
                <fullName>Class B Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class B Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Native Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class B Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class C Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class C Liquor License</fullName>
            </value>
            <value>
                <fullName>Class C Native Wine</fullName>
            </value>
            <value>
                <fullName>Class D Liquor License</fullName>
            </value>
            <value>
                <fullName>Class E Liquor License</fullName>
            </value>
            <value>
                <fullName>Direct Shipper License</fullName>
            </value>
            <value>
                <fullName>Distiller's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>High Proof Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>High Proof Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Liquor Manufacturer</fullName>
            </value>
            <value>
                <fullName>Micro-Distilled Spirits Permit</fullName>
            </value>
            <value>
                <fullName>Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Native Wine Manufacturer</fullName>
            </value>
            <value>
                <fullName>Special Class C Liquor</fullName>
            </value>
            <value>
                <fullName>Vintner's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Wholesale Wine Distributor</fullName>
            </value>
            <value>
                <fullName>Brew Pub</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>High Proof Brew Pub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/abd_License_Types__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_LicenseType.cls
public without sharing class DX_LicenseType {
	
	@AuraEnabled
    public static string getClass(String code) {

    	// Using the code passed in, go read the license type object and return the class (abd_License_Types__c.abd_Class__c)
    	// If there's an error, set the first word as error - so the client controller can tell the difference
    	// between something working and dying

    	//The code passed in here is defined as an attribute on the Community builder for the component.
    	//It *should* be sourced from: 'abd_License_Types__c.abd_License_Type__c'

    	if (code == null || code == '') return 'ERROR 01: Missing required field.';

    	List<abd_License_Types__c> ltList = [SELECT Id, Name, abd_Class__c, abd_License_Type__c FROM abd_License_Types__c WHERE abd_License_Type__c = :code];

    	if (ltList.isEmpty()) return 'ERROR 05: Unable to locate license type.';

    	return ltList[0].abd_Class__c;

    }
}