force-app/main/default/objects/DX_HelpText__c/DX_HelpText__c.object-meta.xml
<CustomObject>
    <description>Holds Help Text associated with a keyword. A use is to provide help text for stages of an application process.</description>
    <label>DX_HelpText</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DX_HelpText</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DX_HelpText__c/fields/HelpText__c.field-meta.xml
<CustomField>
    <fullName>HelpText__c</fullName>
    <description>Help Text to display</description>
    <label>HelpText</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DX_HelpTextController.cls
public without sharing class DX_HelpTextController {

    // Get the values from the metadata based upon the value passed in.
    // We could read all of the text and hold it here, instead of doing round trips.  Need to think about that one.

    @AuraEnabled
    public static String getHelpText(String keyvalue){
    	DX_HelpText__c ht = [Select HelpText__c from DX_HelpText__c where Name = :keyvalue];
    	if (ht == null) return null;
    	return ht.HelpText__c;
    }
}