force-app/main/default/objects/MUSW__Parcel__c/MUSW__Parcel__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/MUSW__Permit2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Permit2__c/fields/MUSW__Parcel__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Parcel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parcel</label>
    <referenceTo>MUSW__Parcel__c</referenceTo>
    <relationshipLabel>Permits</relationshipLabel>
    <relationshipName>Permit2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Permit2__c/recordTypes/All.recordType-meta.xml
<RecordType>
    <fullName>All</fullName>
    <active>true</active>
    <label>All</label>
</RecordType>

force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Permit2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Permit2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permit</label>
    <referenceTo>MUSW__Permit2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Submission_DateTime__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Submission_DateTime__c</fullName>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DX_SubmissionsManageController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class DX_SubmissionsManageController_Test {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        BGBK.RulesEngineState.setLock();
        
        BGCM.TestMock tm = new BGCM.TestMock();
        
        MUSW__Parcel__c par = (MUSW__Parcel__c )tm.mk('MUSW__Parcel__c');
        MUSW__Permit2__c perm = (MUSW__Permit2__c )tm.mkc('MUSW__Permit2__c',par.Id);
        MUSW__Submission__c s = (MUSW__Submission__c)tm.mkc('MUSW__Submission__c',perm.Id);
        //this insert will have a CreatedDate date time.  
        FeedItem fi = (FeedItem)tm.mk('FeedItem',new Map<String, Object>{'ParentId' => s.id,'body' => 'abc'});
        FeedItem[] fs = [select CreatedDate from FeedItem where ParentId=:s.id order by CreatedDate DESC limit 1];
        
        BGBK.RulesEngineState.releaseLock();
        
        pageReference p = Page.DX_SubmissionsManage;
        p.getParameters().put('id', perm.Id);
        Test.setCurrentPage(p); 
        
        DX_SubmissionsManageController c= new DX_SubmissionsManageController ();
        c.currentSub  = s.id;
        c.publisher = true;
        c.save();
        
        MUSW__Submission__c s1 = [select id,MUSW__Submission_DateTime__c from MUSW__Submission__c  where id=:s.id limit 1];
        System.assert(s1.MUSW__Submission_DateTime__c != null);
        FeedItem fi2 = [select id,ParentId,CreatedDate from FeedItem where ParentId=:s.id order by CreatedDate DESC limit 1];
        System.assertEquals(true, fi2 != null);
        System.assertEquals(fs[0].CreatedDate , fi2.CreatedDate);
        System.assertEquals(s.id, fi2.ParentId);
    }
}