force-app/main/default/objects/dx_cmpNavigation__mdt/dx_cmpNavigation__mdt.object-meta.xml
<CustomObject>
    <description>Holds the component navigation, and some display characteristics</description>
    <label>dx_cmpNavigation</label>
    <pluralLabel>dx_cmpNavigation</pluralLabel>
</CustomObject>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/CmpHome__c.field-meta.xml
<CustomField>
    <fullName>CmpHome__c</fullName>
    <description>If they cancel, here is the home component</description>
    <label>CmpHome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/DetailCmp__c.field-meta.xml
<CustomField>
    <fullName>DetailCmp__c</fullName>
    <description>Name of the detail page for this item.  Used for navigating from the list page to the individual form</description>
    <label>DetailCmp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/NextCmp__c.field-meta.xml
<CustomField>
    <fullName>NextCmp__c</fullName>
    <description>developer name of the next component to display</description>
    <label>NextCmp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/PrevCmp__c.field-meta.xml
<CustomField>
    <fullName>PrevCmp__c</fullName>
    <description>Component to display when previous button is pushed</description>
    <label>PrevCmp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/SaveAddLabel__c.field-meta.xml
<CustomField>
    <fullName>SaveAddLabel__c</fullName>
    <defaultValue>"Save and Add another"</defaultValue>
    <label>SaveAddLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowExitNoSaveButton__c.field-meta.xml
<CustomField>
    <fullName>ShowExitNoSaveButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowExitNoSaveButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowNextButton__c.field-meta.xml
<CustomField>
    <fullName>ShowNextButton__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ShowNextButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowSaveAddButton__c.field-meta.xml
<CustomField>
    <fullName>ShowSaveAddButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowSaveAddButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowSaveExitButton__c.field-meta.xml
<CustomField>
    <fullName>ShowSaveExitButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowSaveExitButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowSkipButton__c.field-meta.xml
<CustomField>
    <fullName>ShowSkipButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowSkipButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/SkipLabel__c.field-meta.xml
<CustomField>
    <fullName>SkipLabel__c</fullName>
    <defaultValue>"Skip this"</defaultValue>
    <label>SkipLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/Valid_for_App_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_App_Record_Types__c</fullName>
    <description>Describes the application types that this navigation and display will work for.  Can be used to tailor navigation or button display for a specific app record type.</description>
    <label>Valid for App Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ValidLicenseTypeList__c.field-meta.xml
<CustomField>
    <fullName>ValidLicenseTypeList__c</fullName>
    <description>Looks like a multi-select picklist of license types that this screen should appear on.</description>
    <label>ValidLicenseTypeList</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/Primary_Lic_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Lic_Type__c</fullName>
    <formula>TEXT(abd_Primary_License__r.abd_License_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary_Lic_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Related Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Review__c/MUSW__Review__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <label>Review</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Review__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dx_StdPageAbstraction.cls
public with sharing class dx_StdPageAbstraction {
    
@AuraEnabled
  public static Navigation_Information getNavigationModel(String objectId) {
// System.debug('STDPageAbstraction ObjectId ' + objectId);

    list<dx_cmpNavigation__mdt> navRecs = [Select MasterLabel, NextCmp__c, PrevCmp__c, DetailCmp__c, ShowNextButton__c, ShowSaveExitButton__c, 
    										    ShowExitNoSaveButton__c, ShowSkipButton__c, SkipLabel__c, ShowSaveAddButton__c, SaveAddLabel__c, 
    										    CmpHome__c, ValidLicenseTypeList__c, Valid_for_App_Record_Types__c from dx_cmpNavigation__mdt];

    String lt = null;
    String recordType = null;
    Boolean isApplication = false;
    //  We can be called with an invalid record id which should just fall through.                                          
    	if (!String.isBlank(objectId) && objectId.length() >= 15) {
			
			//  object id can be an application ID, or a license ID at this time. 
            if (objectId.left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
                isApplication = true;
                list<MUSW__Application2__c> app_ltList = [Select Primary_Lic_Type__c, RecordType.Name, abd_Application_Type__c from MUSW__Application2__c where id = :objectId limit 1];
        	    if (app_ltList.size() > 0) {
                    lt = app_ltList[0].Primary_Lic_Type__c;
                    recordType = app_ltList[0].RecordType.Name;
                    if (recordType == 'New Application' && app_ltList[0].abd_Application_Type__c == 'Add Privilege or License to Existing License')
                        recordType = 'Add Privilege';
//                    'Ownership Update';
                }
            }
            else {      
            // if this is a license object, then grab the type and the primary license.  If it points to another record (really another record), then go
            // get the license type from the other record (should be the primary, since we don't allow more than 1 level)
                if (objectId.left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
                    list<MUSW__License2__c> lic_ltList = [Select abd_License_Type__c, abd_Primary_License__r.Id from MUSW__License2__c where id = :objectId limit 1];
                    if (lic_ltList.size() > 0 && lic_ltList[0].abd_Primary_License__r.Id != null)
                        if (lic_ltList[0].abd_Primary_License__r.Id != objectId)
                            lic_ltList = [Select abd_License_Type__c from  MUSW__License2__c where id = :lic_ltList[0].abd_Primary_License__r.Id limit 1];
                    if (lic_ltList.size() > 0)
                        lt = lic_ltList[0].abd_License_Type__c;
                }
                else if (objectId.left(3) == Schema.SObjectType.MUSW__Review__c.getKeyPrefix()){
					Id appId = [select MUSW__Application2__c from MUSW__Review__c where Id=:objectId].MUSW__Application2__c;
					list<MUSW__Application2__c> app_ltList = [Select Primary_Lic_Type__c, RecordType.Name, abd_Application_Type__c from MUSW__Application2__c where id = :appId limit 1];
	        	    if (app_ltList.size() > 0) {
	                    lt = app_ltList[0].Primary_Lic_Type__c;
	                    recordType = app_ltList[0].RecordType.Name;
                        if (recordType == 'New Application' && app_ltList[0].abd_Application_Type__c == 'Add Privilege or License to Existing License')
                            recordType = 'Add Privilege';
	                }
				}
				   
            }
        }
        return new Navigation_Information(lt, navRecs, isApplication, recordType, Site.getBaseUrl());
    }

    // Special class to return to the lightning component.

    public class Navigation_Information {


    	public Navigation_Information(String licenseType, List<dx_cmpNavigation__mdt> navigationModel, Boolean isApplication, String recordType, String sitePrefix) {
            this.licenseType = licenseType;
            this.navigationModel = navigationModel;
            this.isApplication = isApplication;
            this.recordType = recordType;
            this.sitePrefix = sitePrefix;
        }
    	@AuraEnabled public String licenseType {get; set;}

		@AuraEnabled public List<dx_cmpNavigation__mdt> navigationModel {get; set;}

        @AuraEnabled public Boolean isApplication {get; set;}

        @AuraEnabled public String recordType {get; set;}

        @AuraEnabled public String sitePrefix {get; set;}
    }
}