force-app/main/default/objects/dx_cmpNavigation__mdt/dx_cmpNavigation__mdt.object-meta.xml
<CustomObject>
    <description>Holds the component navigation, and some display characteristics</description>
    <label>dx_cmpNavigation</label>
    <pluralLabel>dx_cmpNavigation</pluralLabel>
</CustomObject>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/CmpHome__c.field-meta.xml
<CustomField>
    <fullName>CmpHome__c</fullName>
    <description>If they cancel, here is the home component</description>
    <label>CmpHome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/NextCmp__c.field-meta.xml
<CustomField>
    <fullName>NextCmp__c</fullName>
    <description>developer name of the next component to display</description>
    <label>NextCmp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/PrevCmp__c.field-meta.xml
<CustomField>
    <fullName>PrevCmp__c</fullName>
    <description>Component to display when previous button is pushed</description>
    <label>PrevCmp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/SaveAddLabel__c.field-meta.xml
<CustomField>
    <fullName>SaveAddLabel__c</fullName>
    <defaultValue>"Save and Add another"</defaultValue>
    <label>SaveAddLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowExitNoSaveButton__c.field-meta.xml
<CustomField>
    <fullName>ShowExitNoSaveButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowExitNoSaveButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowNextButton__c.field-meta.xml
<CustomField>
    <fullName>ShowNextButton__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ShowNextButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowSaveAddButton__c.field-meta.xml
<CustomField>
    <fullName>ShowSaveAddButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowSaveAddButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowSaveExitButton__c.field-meta.xml
<CustomField>
    <fullName>ShowSaveExitButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowSaveExitButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/ShowSkipButton__c.field-meta.xml
<CustomField>
    <fullName>ShowSkipButton__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShowSkipButton</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/dx_cmpNavigation__mdt/fields/SkipLabel__c.field-meta.xml
<CustomField>
    <fullName>SkipLabel__c</fullName>
    <defaultValue>"Skip this"</defaultValue>
    <label>SkipLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ca_body.cls
public with sharing class ca_body {
    
@AuraEnabled
    public static list<dx_cmpNavigation__mdt> getNavigationModel() {
    	system.debug('getNavigtionModel invoked');
    	list<dx_cmpNavigation__mdt> navRecs = [Select DeveloperName, MasterLabel, NextCmp__c, PrevCmp__c, ShowNextButton__c, ShowSaveExitButton__c, 
    										    ShowExitNoSaveButton__c, ShowSkipButton__c, SkipLabel__c, ShowSaveAddButton__c, SaveAddLabel__c, 
    										    CmpHome__c from dx_cmpNavigation__mdt];

    	return navRecs;
    }
}