force-app/main/default/objects/BGBL__Applied_Query__c/BGBL__Applied_Query__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Queries required by letter including any unique instructions eg. order, parent query and attach</description>
    <label>Letter Applied Query</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applied Letter Queries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Applied_Query__c/fields/BGBL__Batch_Letter__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Batch_Letter__c</fullName>
    <label>Letter</label>
    <referenceTo>BGBL__Batch_Letter__c</referenceTo>
    <relationshipLabel>Applied Letter Queries</relationshipLabel>
    <relationshipName>Applied_Queries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BGBL__Applied_Query__c/fields/BGBL__Child_Iterate_Query__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Child_Iterate_Query__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>if true, each record returned by this query will result in a letter copy</inlineHelpText>
    <label>Child Iterate Query</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BGBL__Applied_Query__c/fields/BGBL__Query__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Query__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Query</label>
    <referenceTo>BGBL__Query__c</referenceTo>
    <relationshipName>Applied_Queries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter__c/BGBL__Batch_Letter__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Single and Batch letter configuration</description>
    <label>Letter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Batch_Letter__c/fields/BGBL__File_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>BGBL__File_Name_Prefix__c</fullName>
    <inlineHelpText>Files attached to parent records (e.g., Contacts) will utilize this "friendly" name plus a timestamp</inlineHelpText>
    <label>File Name Prefix</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter__c/fields/BGBL__Merge_Template__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Merge_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merge Template</label>
    <referenceTo>BGBL__Merge_Template__c</referenceTo>
    <relationshipName>Batch_Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter__c/fields/BGBL__Output_Type_Short__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Output_Type_Short__c</fullName>
    <formula>IF(ispickval( BGBL__Output_Type__c ,"Acrobat (.pdf)"), "pdf","") + 
IF(ispickval( BGBL__Output_Type__c ,"Word 2003 or earlier (.doc)"), "doc","") +
IF(ispickval( BGBL__Output_Type__c ,"Word 2007 (.docx)"), "docx","")</formula>
    <label>Output Type (short)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGBL__Merge_Template__c/BGBL__Merge_Template__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Stores latest attached document and versions</description>
    <label>Letter Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letter Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Query__c/BGBL__Query__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Query definitions including fields, where clause, etc</description>
    <label>Letter Query</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letter Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DRELetterManager.cls
/**
 *  Provides data related BGBL letters to DRE
 */
public class DRELetterManager
{
    public static Id getLetterId(String letterName)
    {
        SObject letter = getLetter(letterName);
        return (letter != null) ? letter.Id : null;
    }
    
    public static String getLetterOutputType(String letterName)
    {
        SObject letter = getLetter(letterName);
        return (letter != null) ? (String)letter.get('BGBL__Output_Type_Short__c') : null;
    }
    
    /**
     *  child tables referenced in Applied Queries must be specified in Scope
     */
    public static String getChildrenIds(String letterName, DRE.DREResultContext rc)
    {
        String childIdsStr = null;
        SObject letter = getLetter(letterName);
        
        // if children are needed for the letter, get them from the filters
        if (letter.getSObjects('BGBL__Applied_Queries__r') != null)
        {
            for (SObject appliedQ : letter.getSObjects('BGBL__Applied_Queries__r'))
            {
                if ((Boolean)appliedQ.get('BGBL__Child_Iterate_Query__c'))
                {
                    String childName = (String)appliedQ.getSObject('BGBL__Query__r').get('BGBL__Object_Name__c');
                    
                    // add children Ids from Scope records
                    Id[] childIds = new Id[]{};
                    for (DRE.DREResultContext.ResultScopeVO rs : rc.getScopeRecords())
                    {
                        if (rs.getRecord().getSObjectType_Str() == childName)
                        {
                            childIds.add(rs.getRecord().getId());
                        }
                    }
                    
                    if (!childIds.isEmpty())
                    {
                        childIdsStr = '';
                        for (Id oid : childIds) childIdsStr += ',' + oid;
                        childIdsStr = childIdsStr.replaceFirst(',', '');
                    }
                    
                    break;
                }
            }
        }
        
        return childIdsStr;
    }
    
    public static SObject getLetter(String letterName)
    {
        SObject[] lettersByName = new SObject[]{};
        for (SObject letter : letters)
        {
            if (letter.get('Name') == letterName) lettersByName.add(letter);
        }
        
        if (lettersByName.size() > 1)
        {
            throw new LetterException('Duplicate Batch Letters called "' + letterName + '" were found.');
        }
        else if (lettersByName.size() == 0)
        {
            throw new LetterException('The Batch Letter "' + letterName + '" referenced in a DRE Rule could not be found.');
        }
        
        return lettersByName[0];
    }
    
    private static SObject[] letters
    {
        get
        {
            if (letters == null)
            {
                // get all letters using dynamic query in case letters package isn't installed
                letters = database.query('select Id, Name, BGBL__File_Name_Prefix__c, BGBL__Merge_Template__c, BGBL__Output_Type_Short__c, (select Id, BGBL__Child_Iterate_Query__c, BGBL__Query__r.BGBL__Object_Name__c from BGBL__Applied_Queries__r where BGBL__Child_Iterate_Query__c = true) from BGBL__Batch_Letter__c');
            }
            
            return letters;
        }
        set;
    }
    
    public class LetterException extends Exception {}
}