force-app/main/default/objects/Account/fields/abd_DBA__c.field-meta.xml
<CustomField>
    <fullName>abd_DBA__c</fullName>
    <label>DBA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_DBA__c.field-meta.xml
<CustomField>
    <fullName>abd_DBA__c</fullName>
    <inlineHelpText>Business name</inlineHelpText>
    <label>Doing Business As</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_MyMap.cls
public class DX_MyMap {
    
    @AuraEnabled
    public static list<mapPoint> getPremises(){
        system.debug('Apex is Called');
        list<mapPoint> lm = new list<mapPoint>();
        for(MUSW__Application2__c a:[Select Id,abd_DBA__c,abd_Premises_Geolocation__latitude__s,abd_Premises_Geolocation__longitude__s,
										MUSW__Account__r.Name	 
										from MUSW__Application2__c where abd_Premises_Geolocation__latitude__s!=null]){
        	lm.add(new mapPoint(a));                                 
        }
        if(lm.size()<=0)
            lm.add(new mapPoint('Home of Dreamforce',37.784173, -122.401557));
    	return lm;	    
    }
	
    public class mapPoint{
        
        public mapPoint(MUSW__Application2__c app){
        	this.label = (app.abd_DBA__c!=null)?app.abd_DBA__c:app.MUSW__Account__r.Name;
            this.y = app.abd_Premises_Geolocation__latitude__s;
            this.x = app.abd_Premises_Geolocation__Longitude__s;    
        }
        public mapPoint(string l, decimal y, decimal x){
        	this.label = l;
            this.y = y;
            this.x = x;    
        }
        
        @AuraEnabled
        public string label {get;set;}
        @AuraEnabled
        public decimal y {get;set;}
        @AuraEnabled
        public decimal x {get;set;}
    }
}