force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Liability Company</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Municipality</fullName>
            </value>
            <value>
                <fullName>Non-profit Association</fullName>
            </value>
            <value>
                <fullName>Privately-Held Corporation</fullName>
            </value>
            <value>
                <fullName>Publicly Traded Corporation</fullName>
            </value>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>Foreign corporation as defined in section 504.141</fullName>
                <isActive>false</isActive>
                <label>Foreign corporation as defined in section 504.141</label>
            </value>
            <value>
                <fullName>Nonprofit corporation organized under chapter 504</fullName>
                <isActive>false</isActive>
                <label>Nonprofit corporation organized under chapter 504</label>
            </value>
            <value>
                <fullName>Nonprofit entity which has a principal office in the State of Iowa</fullName>
                <isActive>false</isActive>
                <label>Nonprofit entity which has a principal office in the State of Iowa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Contact__c/Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>APC-{000000}</displayFormat>
        <label>Application Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Contact__c/fields/abd_EIN__c.field-meta.xml
<CustomField>
    <fullName>abd_EIN__c</fullName>
    <description>Used for State EIN typically on this object, but it could be a Federal EIN as well.</description>
    <label>EIN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_Federal_Gambling_Stamp__c.field-meta.xml
<CustomField>
    <fullName>abd_Federal_Gambling_Stamp__c</fullName>
    <label>Federal Gambling Stamp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_LicenseeBusinessType__c.field-meta.xml
<CustomField>
    <fullName>abd_LicenseeBusinessType__c</fullName>
    <formula>Text(Application__r.MUSW__Account__r.Business_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LicenseeBusinessType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_Primary_Owner__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/abd_State_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>abd_State_of_Incorporation__c</fullName>
    <label>State of Incorporation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>BGCK__Answer__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <label>Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/of_Ownership__c.field-meta.xml
<CustomField>
    <fullName>of_Ownership__c</fullName>
    <label>% of Ownership</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>11</length>
    <maskChar>X</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/U_S_Citizen__c.field-meta.xml
<CustomField>
    <fullName>U_S_Citizen__c</fullName>
    <label>U.S. Citizen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/BGCK__Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Answer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Question__c/BGCK__Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Question__c/fields/BGCK__Question__c.field-meta.xml
<CustomField>
    <fullName>BGCK__Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>BGCK__Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_OwnerForm.cls
public without sharing class DX_OwnerForm {
	static String notAnswered = '--None--';
	
	@AuraEnabled
	public static string[] getPicklistValues(){
		List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Application_Contact__c.State__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        system.debug(options);
        return options;
	}
    
    @AuraEnabled
	public static Application_Contact__c getOwnerss(Id ownerId, Id appId){
		Application_Contact__c owner;

		if (ownerId != null) {
			list<Application_Contact__c> ownerlist = [Select Id,Application__c,Business_Name__c,First_Name__c,Last_Name__c,Address__c,
					Address_2__c,City__c,State__c,Zip_Code__c,abd_State_of_Incorporation__c,abd_Primary_Owner__c,Position__c,SSN__c,
					abd_Federal_Gambling_Stamp__c,Date_of_Birth__c,U_S_Citizen__c,of_Ownership__c, abd_LicenseeBusinessType__c, abd_EIN__c
					from Application_Contact__c where Id=:ownerId];	 
			if (ownerlist.size() > 0)
				owner = ownerlist[0];
		}

		if (owner == null)
				owner = new Application_Contact__c(Application__c = appId ,Business_Name__c='',First_Name__c='',Last_Name__c='',Address__c='',Address_2__c='',City__c='',Zip_Code__c='',
					abd_Primary_Owner__c=false,Position__c='',SSN__c='');

		return owner;
	}
	
	@AuraEnabled
    public static string getTypess(ID appId){
        
        User u = [Select Contact.AccountId From User Where Id = :UserInfo.getUserId()];
        // if this fails (user timed out), then we need to 
        if (u == (User)null || u.ContactId == null || u.Contact.AccountId == null) return null;

        list<Account> ac = [Select Business_Type__c from Account where Id in (select MUSW__Account__c from MUSW__Application2__c where ID =: appId) limit 1];
        if (ac.size() > 0) {
        	return ac[0].Business_Type__c;
        }
        return null;
    }
    
    // Update the record - called from Lightning component.  The lightning component handles the validation now. 


    @AuraEnabled
    public static String upRecordApex(Application_Contact__c owner){
        try{
        	list<BGCK__Answer__c> answer = [select Id, Name from BGCK__Answer__c where Application__c =: owner.Application__c and BGCK__Question__r.Name='Owner Details' limit 1];
        	if (answer.size() > 0) {
	        	owner.Answer__c = answer[0].Id;
	        	upsert owner;
	        	list<AggregateResult> AnsCountRecs = [Select Count(Id) from Application_Contact__c where Answer__c=:answer[0].Id];
	        	Object ansCount = AnsCountRecs[0].get('expr0');
	        	answer[0].Name = string.valueOf(ansCount) +' related record(s)';
	        	update answer;
			}
       	}
        catch(exception ex){
            throw new AuraHandledException (ex.getMessage());
        }
        
        return null;
    }  
 
}