force-app/main/default/objects/abd_Authorized_Agent__c/abd_Authorized_Agent__c.object-meta.xml
<CustomObject>
    <label>Authorized Agent</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Authorized Agents</relationshipLabel>
    <relationshipName>Authorized_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Authorized Agents</relationshipLabel>
    <relationshipName>Authorized_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>APC-{000000}</displayFormat>
        <label>Application Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Contact__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/BGCK__Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Answer__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Each answer should be tied to a license for a specific time frame.</description>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__License2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__License2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__License2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__License2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_ApplicationCleanup_BatchTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class DX_ApplicationCleanup_BatchTest {

    @testSetup 
	static void setup() {
        TestUtils.Create_Citizen_Account();
        TestUtils.SetRoleForCurrentUser();
    }
    
    static testMethod void myUnitTest() {
		
		Account acc = TestUtils.Create_Account('Customer', 1)[0];
        Contact c = TestUtils.Create_Contacts(1, acc)[0];
        User pu = TestUtils.CreatePortalUser(c);
        MUSW__Application2__c a = TestUtils.CreateApplication(pu,c,acc,'LE','Class E Liquor License');
		MUSW__License2__c l = [Select Id from MUSW__License2__c][0];
		abd_License_Application__c la= new abd_License_Application__c(abd_Application__c = a.Id, abd_License__c = l.Id);
		insert la;
		BGCK__Answer__c ans = new BGCK__Answer__c(Application__c = a.Id);
		insert ans;
		MUSW__Fee__c f= new MUSW__Fee__c(MUSW__Application2__c = a.Id);
		insert f;
		abd_Authorized_Agent__c aa = new abd_Authorized_Agent__c(abd_Application__c = a.Id);
		insert aa;
		MUSW__Submission__c sub = new MUSW__Submission__c(MUSW__Application2__c = a.Id);
		insert sub;
		
		Application_Contact__c ac = TestUtils.Create_ApplicationContact(a,c);
		
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM MUSW__Application2__c'));
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM BGCK__Answer__c'));
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM MUSW__Fee__c'));
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM abd_Authorized_Agent__c'));
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM MUSW__Submission__c'));
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM Application_Contact__c'));
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM MUSW__License2__c'));
		System.AssertEquals(1,database.countquery('SELECT COUNT() FROM abd_License_Application__c'));
		
		Test.StartTest();
		DX_ApplicationCleanup_Batch cleanup = new DX_ApplicationCleanup_Batch();
		ID batchprocessid = Database.executeBatch(cleanup,200);
		system.debug(batchprocessid);
		Test.StopTest();
	
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM MUSW__Application2__c'));  
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM BGCK__Answer__c'));
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM MUSW__Fee__c'));
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM abd_Authorized_Agent__c'));
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM MUSW__Submission__c'));
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM Application_Contact__c'));
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM MUSW__License2__c'));
		System.AssertEquals(0,database.countquery('SELECT COUNT() FROM abd_License_Application__c'));
		
	}
}