force-app/main/default/objects/abd_Authorized_Agent__c/abd_Authorized_Agent__c.object-meta.xml
<CustomObject>
    <label>Authorized Agent</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Authorized Agents</relationshipLabel>
    <relationshipName>Authorized_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Auth_Agent_Address_2__c.field-meta.xml
<CustomField>
    <fullName>abd_Auth_Agent_Address_2__c</fullName>
    <label>Address 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Auth_Agent_Address__c.field-meta.xml
<CustomField>
    <fullName>abd_Auth_Agent_Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Auth_Agent_City__c.field-meta.xml
<CustomField>
    <fullName>abd_Auth_Agent_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Auth_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>abd_Auth_Agent_Name__c</fullName>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Auth_Agent_Phone__c.field-meta.xml
<CustomField>
    <fullName>abd_Auth_Agent_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Auth_Agent_State__c.field-meta.xml
<CustomField>
    <fullName>abd_Auth_Agent_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Auth_Agent_Zip__c.field-meta.xml
<CustomField>
    <fullName>abd_Auth_Agent_Zip__c</fullName>
    <label>Zip</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <formula>text(abd_License__r.abd_License_Type__c )</formula>
    <label>License_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DX_AuthorizedAgentForm.cls
public without sharing class DX_AuthorizedAgentForm {
	static String notAnswered = '--None--';
	
	@AuraEnabled
	public static string[] getPicklistValues(){
		List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = abd_Authorized_Agent__c.abd_Auth_Agent_State__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        
        return options;
	}
    
    @AuraEnabled
	public static abd_Authorized_Agent__c getAA(Id agentId){

		abd_Authorized_Agent__c agent;
		if (agentId != null) {
			list<abd_Authorized_Agent__c> agentlist = [Select Id,abd_Application__c,abd_Auth_Agent_Name__c,abd_Auth_Agent_Address__c,abd_Auth_Agent_Address_2__c,
					abd_Auth_Agent_City__c,abd_Auth_Agent_State__c,abd_Auth_Agent_Zip__c,abd_Auth_Agent_Phone__c
					from abd_Authorized_Agent__c where Id=:agentId];	 

			if (agentlist.size() > 0) agent = agentlist[0];
		}

		if (agent == null)
			agent = new abd_Authorized_Agent__c(abd_Application__c = null,abd_Auth_Agent_Name__c='',abd_Auth_Agent_Address__c='',
												abd_Auth_Agent_Address_2__c='',abd_Auth_Agent_City__c='',abd_Auth_Agent_Zip__c='');
		return agent;
	}
	
	/*@AuraEnabled
	public static MUSW__Application2__c getApplication(Id appId){
		MUSW__Application2__c app = [Select Id,(select id, abd_License_Type__c from License_Applications__r) from MUSW__Application2__c where Id=:appId];
		set<string> ss = new set<string>{'CB', 'CD', 'CV'};	 
		for(abd_License_Application__c la:app.License_Applications__r){
			if(ss.contains(la.abd_License_Type__c))
				return app;
		}
		return null;
	}*/
	
	@AuraEnabled
	public static boolean checkApplication(Id appId){
		MUSW__Application2__c app = [Select Id,(select id, abd_License_Type__c from License_Applications__r) from MUSW__Application2__c where Id=:appId];
		set<string> ss = new set<string>{'CB', 'CD', 'CV', 'SP'};	 
		for(abd_License_Application__c la:app.License_Applications__r){
			if(la.abd_License_Type__c=='SP')
				return true;
			if(ss.contains(la.abd_License_Type__c))
				return false;
		}
		return null;
	}
	
	// Update the record - called from Lightning component.  The lightning component handles the validation now. 

    @AuraEnabled
    public static String upRecordApex(abd_Authorized_Agent__c agent){
        system.debug('Agent Update');
        try{
        	upsert agent;
        }catch(exception ex){
            return ex.getMessage();
        }
        
        return null;
    }    
}