force-app/main/default/objects/abd_Authorized_Agent__c/abd_Authorized_Agent__c.object-meta.xml
<CustomObject>
    <label>Authorized Agent</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Authorized Agents</relationshipLabel>
    <relationshipName>Authorized_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_Authorized_Agent__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Authorized Agents</relationshipLabel>
    <relationshipName>Authorized_Agents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/Application_Contact__c.object-meta.xml
<CustomObject>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>APC-{000000}</displayFormat>
        <label>Application Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Contact__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>BGCK__Answer__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Contact__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Application Contacts</relationshipLabel>
    <relationshipName>Application_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/BGCK__Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGCK__Answer__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Each answer should be tied to a license for a specific time frame.</description>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGCK__Answer__c/fields/License_Application__c.field-meta.xml
<CustomField>
    <fullName>License_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License-Application</label>
    <referenceTo>abd_License_Application__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>DRAM Review</fullName>
            </value>
            <value>
                <fullName>Local Authority Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 1 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 2 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 3 Review</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Fee__c/MUSW__Fee__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Fee__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Submission__c/MUSW__Submission__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Tracks online files</description>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Submission__c/fields/MUSW__Application2__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Application2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_ApplicationCleanup_Batch.cls
global class DX_ApplicationCleanup_Batch implements Database.Batchable<sObject>{ 
	
	global Database.QueryLocator start(Database.BatchableContext BC){
   		string [] statuses = new string[]{'In Progress','Pending'};
   		decimal days = [Select Application_Cleanup_Timeframe__c from DX_Portal_General_Setting__mdt][0].Application_Cleanup_Timeframe__c;
   		date d = system.today();
   		d = d.addDays((!test.isRunningTest())?(integer.valueof(days)*-1):1);
   		string query = 'Select Id, (Select Id, abd_License__c From License_Applications__r), (Select Id From Authorized_Agents__r), (Select Id From MUSW__Submissions__r), (Select Id From MUSW__Fees__r), (Select Id From Answers__r), (Select Id From Application_Contacts__r) from MUSW__Application2__c where RecordType.Name != \'Renewal Application\' and MUSW__Status__c IN:statuses and lastmodifieddate<=:d';
		return Database.getQueryLocator(query); 
	}
	     
	global void execute(Database.BatchableContext BC, List<MUSW__Application2__c> scope){
		Id[] deleteList = new Id[]{};
		map<string,set<id>> mapIds = new map<string,set<id>>();
		
		for(MUSW__Application2__c a : scope){ 
			
			if(!mapIds.containskey('App'))
				mapIds.put('App',new set<id>());
			mapIds.get('App').add(a.Id);
			
			if(!mapIds.containskey('LicApp'))
				mapIds.put('LicApp',new set<id>());
			if(!mapIds.containskey('Lic'))
				mapIds.put('Lic',new set<id>());
			for(abd_License_Application__c la: a.License_Applications__r){
				mapIds.get('LicApp').add(la.Id);
				mapIds.get('Lic').add(la.abd_License__c);
			}
			if(!mapIds.containskey('Ans'))
				mapIds.put('Ans',new set<id>());
			for(BGCK__Answer__c ans: a.Answers__r) {	
				mapIds.get('Ans').add(ans.Id);
			}
			if(!mapIds.containskey('Fee'))
				mapIds.put('Fee',new set<id>());
			for(MUSW__Fee__c f : a.MUSW__Fees__r){	
				mapIds.get('Fee').add(f.Id);
			}
			if(!mapIds.containskey('Auth'))
				mapIds.put('Auth',new set<id>());
			for(abd_Authorized_Agent__c aa: a.Authorized_Agents__r){	
				mapIds.get('Auth').add(aa.Id);
			}
			if(!mapIds.containskey('Sub'))
				mapIds.put('Sub',new set<id>());
			for(MUSW__Submission__c sub: a.MUSW__Submissions__r){	
				mapIds.get('Sub').add(sub.Id);
			}
			if(!mapIds.containskey('Own'))
				mapIds.put('Own',new set<id>());
			for(Application_Contact__c ac: a.Application_Contacts__r){	
				mapIds.get('Own').add(ac.Id);
			}	 
		}
		deleteList.addAll(mapIds.get('Lic'));	
		deleteList.addAll(mapIds.get('Ans'));	
		deleteList.addAll(mapIds.get('Fee'));	
		deleteList.addAll(mapIds.get('Auth'));	
		deleteList.addAll(mapIds.get('Sub'));	
		deleteList.addAll(mapIds.get('Own'));	
		deleteList.addAll(mapIds.get('App'));	
		deleteList.addAll(mapIds.get('LicApp'));	
		
		Database.DeleteResult[] drList = Database.delete(deleteList, true);		 
		system.debug(mapIds);
		system.debug(deleteList);
		system.debug(drList);
	}
	     
	global void finish(Database.BatchableContext info){     
	} 

}