force-app/main/default/objects/testobj__c/testobj__c.object-meta.xml
<CustomObject>
    <label>testobj</label>
    <nameField>
        <label>testobj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>testobjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/testobj__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>3</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/classes/testvfcontroller.cls
Public Class testvfcontroller {

public void testone() {

string q = 'select id, Location__Latitude__s, Location__Longitude__s';
q += ' from testobj__c';
q += ' where DISTANCE(Location__c, GEOLOCATION(1,2),\'mi\') < 20 ';
q += ' order by DISTANCE(Location__c, GEOLOCATION( 1,2), \'mi\')';
q += ' limit 10';

system.debug('******************* q: ' + q);
list<testobj__c> seList = Database.query(q);
return;
}
}