force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Application_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Application_Date__c</fullName>
    <inlineHelpText>Date application is submitted for the first time</inlineHelpText>
    <label>Application Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_Address_2__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Address_2__c</fullName>
    <inlineHelpText>Further explanation of location to be licensed</inlineHelpText>
    <label>Premises Address 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_Address__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Address__c</fullName>
    <inlineHelpText>Address of location to be licensed</inlineHelpText>
    <label>Premises Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_County__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_County__c</fullName>
    <label>Premises County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adair</fullName>
            </value>
            <value>
                <fullName>Adams</fullName>
            </value>
            <value>
                <fullName>Allamakee</fullName>
            </value>
            <value>
                <fullName>Appanoose</fullName>
            </value>
            <value>
                <fullName>Audubon</fullName>
            </value>
            <value>
                <fullName>Benton</fullName>
            </value>
            <value>
                <fullName>Black Hawk</fullName>
            </value>
            <value>
                <fullName>Boone</fullName>
            </value>
            <value>
                <fullName>Bremer</fullName>
            </value>
            <value>
                <fullName>Buchanan</fullName>
            </value>
            <value>
                <fullName>Buena Vista</fullName>
            </value>
            <value>
                <fullName>Butler</fullName>
            </value>
            <value>
                <fullName>Calhoun</fullName>
            </value>
            <value>
                <fullName>Carroll</fullName>
            </value>
            <value>
                <fullName>Cass</fullName>
            </value>
            <value>
                <fullName>Cedar</fullName>
            </value>
            <value>
                <fullName>Cerro Gordo</fullName>
            </value>
            <value>
                <fullName>Cherokee</fullName>
            </value>
            <value>
                <fullName>Chickasaw</fullName>
            </value>
            <value>
                <fullName>Clarke</fullName>
            </value>
            <value>
                <fullName>Clay</fullName>
            </value>
            <value>
                <fullName>Clayton</fullName>
            </value>
            <value>
                <fullName>Clinton</fullName>
            </value>
            <value>
                <fullName>Crawford</fullName>
            </value>
            <value>
                <fullName>Dallas</fullName>
            </value>
            <value>
                <fullName>Davis</fullName>
            </value>
            <value>
                <fullName>Decatur</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Des Moines</fullName>
            </value>
            <value>
                <fullName>Dickinson</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_State__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_State__c</fullName>
    <label>Premises State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Zip_Code__c</fullName>
    <label>Premises Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DX_Application_StaticFields.cls
public class DX_Application_StaticFields {
	
    static String notAnswered = '--None--';
	
    // get the values from the application record.
    @AuraEnabled
    public static MUSW__Application2__c getApplication(Id applicationId){
        
        return [Select Id, abd_Effective_Date__c,abd_Application_Date__c,MUSW__Description__c,abd_Premise_Address__c,abd_Premise_Address_2__c,abd_Premise_City__c,abd_Premise_County__c,abd_Premise_State__c,abd_Premise_Zip_Code__c,abd_Temporary_or_Permanent__c from MUSW__Application2__c where Id=:applicationId];
    }

    // Get the list of values for the picklist field and pass them back to the lightning component.
    // Add the -- not answered-- choice as the first value.  If we move to radial buttons, this can all change.
    @AuraEnabled
    public static List<List<String>> getPicklistValues(){
		List<List<String>> pickVals = new List<List<String>>();
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = MUSW__Application2__c.abd_Premise_County__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.add(options);
        options = new List<String>();
        fieldResult = MUSW__Application2__c.abd_Premise_State__c.getDescribe();
        ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.add(options);
        options = new List<String>();
        fieldResult = MUSW__Application2__c.abd_Temporary_or_Permanent__c.getDescribe();
        ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.add(options);
        return pickVals;
    }

    // Update the record - called from Lightning component.  The lightning component handles the validation now. 

    @AuraEnabled
    public static String upRecordApex(MUSW__Application2__c application,MUSW__Application2__c app2){
        system.debug(app2);
        Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.MUSW__Application2__c.fields.getMap();
        for(String fieldName : schemaFieldMap.keySet()){
        	if(app2.get(fieldName)!=null)
                application.put(fieldName,app2.get(fieldName));
        }
        try{
            update application;
        }catch(exception ex){
            return ex.getMessage();
        }
        
        return 'Update Successful';
    }
}