force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DX_UpdatePremiseApplication_Test.cls
@isTest(SeeAllData=true)
private class DX_UpdatePremiseApplication_Test {

	//     @testSetup 
	// static void setup() {
 //        TestUtils.Create_Citizen_Account();
 //        TestUtils.SetRoleForCurrentUser();
 //    }
    
    static testMethod void myUnitTest() {
        TestUtils.Create_Citizen_Account();
        TestUtils.SetRoleForCurrentUser();
        Account a = TestUtils.Create_Account('Customer', 1)[0];
        Contact c = TestUtils.Create_Contacts(1, a)[0];
        User pu = TestUtils.CreatePortalUser(c);

        System.runAs(pu) {
            MUSW__Application2__c app = TestUtils.CreateApplication(pu,c,a,'LE','Class E Liquor License');

            ID licenseId = app.abd_Primary_License__c;
            System.assertNotEquals(licenseId, null);

            MUSW__Application2__c updApp = dx_UpdatePremiseApplication.createApplicationfromLicense(licenseId);
            updApp.MUSW__Description__c = 'test';
            dx_UpdatePremiseApplication.UpdateApplication(updApp);
        }        
    }
}