force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Business_Name__c.field-meta.xml
<CustomField>
    <fullName>abd_Business_Name__c</fullName>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Business_Name__c.field-meta.xml
<CustomField>
    <fullName>abd_Business_Name__c</fullName>
    <inlineHelpText>This is the help text for the Business Name</inlineHelpText>
    <label>Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Class__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Class__c</fullName>
    <inlineHelpText>classification or function/business/privilege permitted   And I helped with this!</inlineHelpText>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brewer's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Broker's Permit</fullName>
            </value>
            <value>
                <fullName>Carrier Permit</fullName>
            </value>
            <value>
                <fullName>Charity Beer Wine and Liquor Auction Permit</fullName>
            </value>
            <value>
                <fullName>Class A Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class B Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Native Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class B Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class C Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class C Liquor License</fullName>
            </value>
            <value>
                <fullName>Class C Native Wine</fullName>
            </value>
            <value>
                <fullName>Class D Liquor License</fullName>
            </value>
            <value>
                <fullName>Class E Liquor License</fullName>
            </value>
            <value>
                <fullName>Direct Shipper License</fullName>
            </value>
            <value>
                <fullName>Distiller's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>High Proof Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>High Proof Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Liquor Manufacturer</fullName>
            </value>
            <value>
                <fullName>Micro-Distilled Spirits Permit</fullName>
            </value>
            <value>
                <fullName>Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Native Wine Manufacturer</fullName>
            </value>
            <value>
                <fullName>Special Class C Liquor</fullName>
            </value>
            <value>
                <fullName>Vintner's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Wholesale Wine Distributor</fullName>
            </value>
            <value>
                <fullName>Brew Pub</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>High Proof Brew Pub</fullName>
            </value>
            <value>
                <fullName>Living Quarters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_CreateNewApplication_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class DX_CreateNewApplication_Test {

    @testSetup 
	static void setup() {
        TestUtils.Create_Citizen_Account();
        TestUtils.SetRoleForCurrentUser();
    }
    
    static testMethod void myUnitTest() {
        Account a = TestUtils.Create_Account('Customer', 1)[0];
        Contact c = TestUtils.Create_Contacts(1, a)[0];
        User pu = TestUtils.CreatePortalUser(c);
        MUSW__Application2__c app = TestUtils.CreateApplication(pu,c,a,'LE','Class E Liquor License');
        
        DX_CreateNewApplication.createNewL(new MUSW__License2__c(abd_Business_Name__c='Test Business',MUSW__Class__c=DX_CreateNewApplication.getLicenseType()[0].name),'',app);
    		
        System.RunAs(pu) {
        	DX_CreateNewApplication.createNewL(new MUSW__License2__c(abd_Business_Name__c='Test Business',MUSW__Class__c=DX_CreateNewApplication.getLicenseType()[0].name, name='1223'),'',app);
    		DX_CreateNewApplication.createNewL(new MUSW__License2__c(abd_Business_Name__c='Test Business'),'',app);
        }
    }
}