force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Acknowledgement__c.field-meta.xml
<CustomField>
    <fullName>abd_Acknowledgement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Acknowledgement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/dx_AttestationAndSubmitController_Test.cls
@isTest
public class dx_AttestationAndSubmitController_Test {

    	@testSetup 
	static void setup() {
        TestUtils.Create_Citizen_Account();
        TestUtils.SetRoleForCurrentUser();
        Account a = TestUtils.Create_Account('Customer', 1)[0];
        Contact c = TestUtils.Create_Contacts(1, a)[0];
        User pu = TestUtils.CreatePortalUser(c);
        MUSW__Application2__c app = TestUtils.CreateApplication(pu,c,a,'LE','Class E Liquor License');
        
    }

    static testMethod void testAttestationAndSubmit() {
        User pu = [select id from user where username='tester@doextra.com'];
        MUSW__Application2__c app = [select id from MUSW__Application2__c where ownerId=:pu.Id];
        System.RunAs(pu) {
            dx_AttestationAndSubmitController dasc = new dx_AttestationAndSubmitController();
            dx_AttestationAndSubmitController.setAcknowledgmentFlag(app.Id);
            MUSW__Application2__c app2 = [select id, abd_Acknowledgement__c from MUSW__Application2__c where ownerId=:pu.Id];
            system.debug(app2);
        	dx_AttestationAndSubmitController.setAcknowledgmentFlag(pu.id);
            
        }
    }    
}