force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>DRAM Review</fullName>
            </value>
            <value>
                <fullName>Local Authority Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 1 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 2 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 3 Review</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/Primary_Lic_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Lic_Type__c</fullName>
    <formula>TEXT(abd_Primary_License__r.abd_License_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary_Lic_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Related Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Class__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Class__c</fullName>
    <inlineHelpText>classification or function/business/privilege permitted   And I helped with this!</inlineHelpText>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brewer's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Broker's Permit</fullName>
            </value>
            <value>
                <fullName>Carrier Permit</fullName>
            </value>
            <value>
                <fullName>Charity Beer Wine and Liquor Auction Permit</fullName>
            </value>
            <value>
                <fullName>Class A Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class B Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Native Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class B Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class C Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class C Liquor License</fullName>
            </value>
            <value>
                <fullName>Class C Native Wine</fullName>
            </value>
            <value>
                <fullName>Class D Liquor License</fullName>
            </value>
            <value>
                <fullName>Class E Liquor License</fullName>
            </value>
            <value>
                <fullName>Direct Shipper License</fullName>
            </value>
            <value>
                <fullName>Distiller's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>High Proof Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>High Proof Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Liquor Manufacturer</fullName>
            </value>
            <value>
                <fullName>Micro-Distilled Spirits Permit</fullName>
            </value>
            <value>
                <fullName>Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Native Wine Manufacturer</fullName>
            </value>
            <value>
                <fullName>Special Class C Liquor</fullName>
            </value>
            <value>
                <fullName>Vintner's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Wholesale Wine Distributor</fullName>
            </value>
            <value>
                <fullName>Brew Pub</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>High Proof Brew Pub</fullName>
            </value>
            <value>
                <fullName>Living Quarters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Timely Filed</fullName>
            </value>
            <value>
                <fullName>In Appeal</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dx_StatusBarAppSummaryController.cls
public without sharing class dx_StatusBarAppSummaryController {
    
    
    @AuraEnabled
    public static MUSW__Application2__c getApplication(String applicationId) {
        
        if (applicationId == null || applicationId == '') return null;
        
        List<MUSW__Application2__c> appList = [SELECT Id, Name, CreatedDate, Primary_Lic_Type__c, MUSW__Status__c, abd_Primary_License__c, abd_Primary_License__r.MUSW__Class__c FROM MUSW__Application2__c WHERE Id = :applicationId ];
        
        if (appList == null || appList.isEmpty()) return null;
        
        return appList[0];
    }
    
    @AuraEnabled
    public static AppStatus getAppStatus (string objectId){
        AppStatus statusBlock = new AppStatus();
        
        if (!String.isEmpty(objectId))  {      // If we have a valid ID
            if (objectId.left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
                statusBlock.isApplication = true;
                List<MUSW__Application2__c> appList = [SELECT Id, Name, CreatedDate, MUSW__Status__c, abd_Primary_License__c, abd_Primary_License__r.MUSW__Class__c 
                                                   		FROM MUSW__Application2__c 
                                                   		WHERE Id = :objectId ];
                if (appList.size() > 0) {           // and we have a record
                    statusBlock.Id = appList[0].Id;
                    statusBlock.name = appList[0].Name;
                    statusBlock.licClass = appList[0].abd_Primary_License__r.MUSW__Class__c;
                    statusBlock.status = appList[0].MUSW__Status__c;
                    statusBlock.created = applist[0].CreatedDate.format();
                    dx_ProgressAndReview_helper prh = new dx_ProgressAndReview_helper(objectId);
                    statusBlock.progressStatus = prh.getStatus();
                }
            }
            else if (objectId.left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
                statusBlock.isApplication = false;                
                 List<MUSW__License2__c> licList = [SELECT Id, Name, CreatedDate, MUSW__Status__c, MUSW__Class__c 
                                                        FROM MUSW__License2__c 
                                                        WHERE Id = :objectId ];
                    if (liclist.size() > 0) {
                        statusBlock.Id = licList[0].Id;
                        statusBlock.name = licList[0].Name;
                        statusBlock.licClass = licList[0].MUSW__Class__c;
                        statusBlock.status = licList[0].MUSW__Status__c;
                        statusBlock.created = licList[0].CreatedDate.format();
                        // dx_ProgressAndReview_helper prh = new dx_ProgressAndReview_helper(objectId);
                        // statusBlock.progressStatus = prh.getStatus();
                    }
            }
        }   
        
        
        return statusBlock;
    }
    
 public class AppStatus {
        @AuraEnabled  public Boolean isApplication {get;set;}
        @AuraEnabled  public String licClass {get;set;}
        @AuraEnabled  public String name {get;set;}
        @AuraEnabled  public String Id {get;set;}
        @AuraEnabled  public String status {get;set;}
        @AuraEnabled  public String created {get;set;}
        @Auraenabled list<dx_ProgressAndReview_helper.SectionStatus> progressStatus {get;set;}
        }
    
    
}