force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Portal_Processed__c.field-meta.xml
<CustomField>
    <fullName>abd_Portal_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>DRAM Review</fullName>
            </value>
            <value>
                <fullName>Local Authority Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 1 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 2 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 3 Review</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_ChangeDramCarrier.cls
public without sharing class DX_ChangeDramCarrier {
    

    @AuraEnabled
    public static MUSW__Application2__c createApplicationfromLicense(ID licenseId) {
        try {
	        User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
	        
	        // if this fails (user timed out), then we need to 
	        if (u == (User)null || u.ContactId == null) return new MUSW__Application2__c();

	        // Create a populate application object .  NOTE THIS DOES NOT HAVE AN ID YET.
	        MUSW__Application2__c newApp = DX_Utils.CreateAppFromLicense(licenseId);
	        return newApp;
	    }catch (exception ex) {
	    	throw new AuraHandledException(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
	    }
	}	


 	@AuraEnabled
    public static list<Account> getDram(){
    	list<Account> temp = new list<Account>();
    	temp.add(new Account(name='--None--'));
       	for(Account a:[Select Id, Name from Account where Type='DRAM Shop' order by Name]){
       		temp.add(a);	
       	} 
       	return temp;
    }

    // insert the record - called from Lightning component.
    @AuraEnabled
    public static String CreateApplication(MUSW__Application2__c application) {
        try{
          // Set the record Type of the application
        application.MUSW__Status__c = 'Pending';
        application.name='System Number';
        application.abd_Application_Type__c = 'Change DRAM';
        application.abd_Portal_Processed__c = true;
        application.RecordTypeId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Dram Carrier Change Application').getRecordTypeId();

        insert application;
        }catch(exception ex){
            throw new AuraHandledException(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
        }

        return application.Id;
    }    
}