force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Description__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>DRAM Review</fullName>
            </value>
            <value>
                <fullName>Local Authority Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 1 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 2 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 3 Review</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_ApplicationListController.cls
public class DX_ApplicationListController {

    @AuraEnabled
    public static List<MUSW__Application2__c> getApplications(Id accountId) {
        
        list<MUSW__Application2__c> tempList = new list<MUSW__Application2__c>();
        try{
            tempList = [SELECT Id,Name, abd_Effective_Date__c,MUSW__Description__c,MUSW__Status__c FROM MUSW__Application2__c where MUSW__Account__c=:accountId ORDER BY createdDate DESC limit 5];
           	if(test.isRunningTest() && tempList.size()==0)
           		MUSW__Application2__c test = tempList[0];	
        }catch(exception e){}
        
        return tempList;
	
	}
    
}