force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_ApplicationForm_Test.cls
@isTest
private class DX_ApplicationForm_Test {
	
	@testSetup 
	static void setup() {
        TestUtils.Create_Citizen_Account();
        TestUtils.SetRoleForCurrentUser();
    }
    
    static testMethod void myUnitTest() {
        Account a = TestUtils.Create_Account('Customer', 1)[0];
        Contact c = TestUtils.Create_Contacts(1, a)[0];
        User pu = TestUtils.CreatePortalUser(c);
        MUSW__Application2__c app = TestUtils.CreateApplication(pu,c,a,'LE','Class E Liquor License');

        // try to get an non existant app - returns an empty app
		System.assertNotEquals(null, DX_ApplicationForm.getApplication(null));
        
        // Get the app we created above and validate that the primary license was set
        app = DX_ApplicationForm.getApplication(app.Id);
        System.assertNotEquals(null, app.abd_Primary_License__c);
        
        // validate the update for the previous app.
        System.assertEquals('Update Successful', DX_ApplicationForm.upRecordApex(app));
        
        // validate that an error message is returned on a null record update.
        System.assertNotEquals(null, DX_ApplicationForm.upRecordApex(new MUSW__Application2__c()));
        
        System.assertNotEquals(null,DX_ApplicationForm.getFieldVisibility());
    }
}