force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Application_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Application_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_PortalWork_LicenseType__c.field-meta.xml
<CustomField>
    <fullName>abd_PortalWork_LicenseType__c</fullName>
    <description>Temporary field used by the Apex - Lightning transport interface for non-persisted objects</description>
    <label>PortalWork_LicenseType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>DRAM Review</fullName>
            </value>
            <value>
                <fullName>Local Authority Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 1 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 2 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 3 Review</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dx_UpdatePremiseApplication.cls
public with sharing class dx_UpdatePremiseApplication {
     // FOR THE UPDATE PREMISE application
    @AuraEnabled
    public static MUSW__Application2__c createApplicationfromLicense(ID licenseId) {
        try {
            User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
            
            // if this fails (user timed out), then we need to 
            if (u == (User)null || u.ContactId == null) 
            	throw new AuraHandledException ('User does not appear to be logged in anymore');

            MUSW__Application2__c application = DX_Utils.CreateAppFromLicense(licenseId);
            application.MUSW__Status__c = 'Pending';
            application.name='System Number';
            application.abd_Application_Type__c = 'Premises Update'; 
			application.RecordTypeId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Premises Update Application').getRecordTypeId();            
            insert application;

            DX_Utils.BuildEmptyAnswers(application.Id, application.abd_Application_Type__c, application.abd_PortalWork_LicenseType__c);

	        return application;

        }catch (exception ex) {
            System.debug(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
            throw new AuraHandledException(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
        }
    }   

    // Update the record - called from Lightning component.  The lightning component handles the validation now. 
    @AuraEnabled
    public static String UpdateApplication(MUSW__Application2__c application) {
        try{
            // Set the record Type of the application
            application.MUSW__Status__c = 'In Progress';
            update application;
        }catch(exception ex){
            throw new AuraHandledException(ex.getLineNumber() + ex.getMessage() + ex.getTypeName());
        }

        return application.Id;
    }    
}