force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_Address__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Address__c</fullName>
    <inlineHelpText>Address of location to be licensed</inlineHelpText>
    <label>Premises Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_State__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_State__c</fullName>
    <label>Premises State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Zip_Code__c</fullName>
    <label>Premises Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_GeocodingController_Test.cls
@isTest
private class DX_GeocodingController_Test {

    @testSetup 
	static void setup() {
        TestUtils.Create_Citizen_Account();
        TestUtils.SetRoleForCurrentUser();
    }
    
    static testMethod void myUnitTest() {
        Account a = TestUtils.Create_Account('Customer', 1)[0];
        Contact c = TestUtils.Create_Contacts(1, a)[0];
        User pu = TestUtils.CreatePortalUser(c);
        MUSW__Application2__c app = TestUtils.CreateApplication(pu,c,a,'LE','Class E Liquor License');
        system.debug(app.id);
        
    	Test.startTest();
    	RestAPIMockImpl mockResponse = new RestAPIMockImpl();
        Test.setMock(HttpCalloutMock.class, mockResponse);
    	
    	PageReference pageRef = Page.DX_Geocoding;
        Test.setCurrentPage(pageRef);
    	
    	ApexPages.StandardController sc = new ApexPages.StandardController(app);
        DX_GeocodingController testGeoCont = new DX_GeocodingController(sc);
        
        testGeoCont.GeocodeAddress();
    	app.abd_Premise_Address__c = 'Test Address';
    	app.abd_Premise_City__c = 'Test City';
    	app.abd_Premise_State__c = 'IA';
    	app.abd_Premise_Zip_Code__c = '12345';
    	update app;
    	sc = new ApexPages.StandardController(app);
        testGeoCont = new DX_GeocodingController(sc);
    	testGeoCont.GeocodeAddress();
    	ArcGIS_RestAPI_Methods rm = new ArcGIS_RestAPI_Methods();
    	rm.GetLocationFromResponse('{"spatialReference": {"wkid": 1234,"latestWkid": 1234},"candidates": [{ "address": "1234 Test St, Mock, State, 12345", "location": {  "x": -75.453453453,  "y": 32.524545345 }, "score": 99, "attributes": {   }, "extent": {  "xmin": -75.453453453,  "ymin": 32.524545345,  "xmax": -75.453453453,  "ymax": 32.524545345 }},{ "address": "1234 Test St, Mock, State, 12345", "location": {  "x": -75.453453453,  "y": 32.524545345 }, "score": 100, "attributes": {   }, "extent": {  "xmin": -75.453453453,  "ymin": 32.524545345,  "xmax": -75.453453453,  "ymax": 32.524545345 }}]}');
    	Test.stopTest();
    }
}