force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Related Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dx_StdPageAbstraction_Test.cls
@isTest
private class dx_StdPageAbstraction_Test {
    static testMethod void testMethod1() {
    	// Create an MUSW application and an MUSW license record
		TestUtils.Create_Citizen_Account();
		list<Account> alist = TestUtils.Create_Account('Licensee', 1);
		System.assertNotEquals(0, alist.size());

		list<Contact> clist = TestUtils.Create_Contacts(1, alist[0]);
		System.assertNotEquals(0, clist.size());
		
		User C = TestUtils.CreatePortalUser(clist[0]);
		System.assertNotEquals(null, C);

    	User U = TestUtils.getTestUserWithRole();
		System.assertNotEquals(null, U);    	

    	MUSW__Application2__c app = TestUtils.CreateApplication(U, clist[0],alist[0], 'BC','Class C Beer Permit');
		System.assertNotEquals(null, app);

    	Id applicationId = app.Id;

    	Id licenseId = app.abd_Primary_License__c;
		System.assertNotEquals(null, licenseId);    	


    	MUSW__License2__c addon = TestUtils.CreateAddOnLicense(U, clist[0],alist[0], 'OS','Outdoor Service',licenseId);
    	Id addOnId = addon.Id;
		System.assertNotEquals(null, addon);    	


    	dx_StdPageAbstraction.getNavigationModel(licenseId);
    	dx_StdPageAbstraction.getNavigationModel(applicationId);
    	dx_StdPageAbstraction.getNavigationModel(addOnId);
        
    }
}