force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <formula>text(abd_License__r.abd_License_Type__c )</formula>
    <label>License_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Bond_Company__c.field-meta.xml
<CustomField>
    <fullName>abd_Bond_Company__c</fullName>
    <inlineHelpText>Company providing bond</inlineHelpText>
    <label>Bond Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bond_Companies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_DRAM_shop__c.field-meta.xml
<CustomField>
    <fullName>abd_DRAM_shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Carrier providing insurance</inlineHelpText>
    <label>Dramshop Liability Insurance Carrier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>DRAM Shop</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications (DRAM shop)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Dues_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>abd_Dues_Member_Number__c</fullName>
    <label>Dues Member Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Non_profit__c.field-meta.xml
<CustomField>
    <fullName>abd_Non_profit__c</fullName>
    <label>Non-profit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Occupancy_Explination__c.field-meta.xml
<CustomField>
    <fullName>abd_Occupancy_Explination__c</fullName>
    <label>Occupancy Explination</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Occupancy_Over_200__c.field-meta.xml
<CustomField>
    <fullName>abd_Occupancy_Over_200__c</fullName>
    <label>Occupancy Over 200</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_County__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_County__c</fullName>
    <label>Premises County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adair</fullName>
            </value>
            <value>
                <fullName>Adams</fullName>
            </value>
            <value>
                <fullName>Allamakee</fullName>
            </value>
            <value>
                <fullName>Appanoose</fullName>
            </value>
            <value>
                <fullName>Audubon</fullName>
            </value>
            <value>
                <fullName>Benton</fullName>
            </value>
            <value>
                <fullName>Black Hawk</fullName>
            </value>
            <value>
                <fullName>Boone</fullName>
            </value>
            <value>
                <fullName>Bremer</fullName>
            </value>
            <value>
                <fullName>Buchanan</fullName>
            </value>
            <value>
                <fullName>Buena Vista</fullName>
            </value>
            <value>
                <fullName>Butler</fullName>
            </value>
            <value>
                <fullName>Calhoun</fullName>
            </value>
            <value>
                <fullName>Carroll</fullName>
            </value>
            <value>
                <fullName>Cass</fullName>
            </value>
            <value>
                <fullName>Cedar</fullName>
            </value>
            <value>
                <fullName>Cerro Gordo</fullName>
            </value>
            <value>
                <fullName>Cherokee</fullName>
            </value>
            <value>
                <fullName>Chickasaw</fullName>
            </value>
            <value>
                <fullName>Clarke</fullName>
            </value>
            <value>
                <fullName>Clay</fullName>
            </value>
            <value>
                <fullName>Clayton</fullName>
            </value>
            <value>
                <fullName>Clinton</fullName>
            </value>
            <value>
                <fullName>Crawford</fullName>
            </value>
            <value>
                <fullName>Dallas</fullName>
            </value>
            <value>
                <fullName>Davis</fullName>
            </value>
            <value>
                <fullName>Decatur</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Des Moines</fullName>
            </value>
            <value>
                <fullName>Dickinson</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premises_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_Premises_Vehicle_Type__c</fullName>
    <label>Premises Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Premises_Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Sell_Gasoline__c.field-meta.xml
<CustomField>
    <fullName>abd_Sell_Gasoline__c</fullName>
    <label>Sell Gasoline</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Square_Footage__c.field-meta.xml
<CustomField>
    <fullName>abd_Square_Footage__c</fullName>
    <label>Square Footage Building Interior</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/Primary_Lic_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Lic_Type__c</fullName>
    <formula>TEXT(abd_Primary_License__r.abd_License_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary_Lic_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/Square_Footage_Retail_Area__c.field-meta.xml
<CustomField>
    <fullName>Square_Footage_Retail_Area__c</fullName>
    <label>Square Footage Retail Area</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Bond_Company__c.field-meta.xml
<CustomField>
    <fullName>abd_Bond_Company__c</fullName>
    <label>Bond Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bond_Companies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_DRAM_Shop__c.field-meta.xml
<CustomField>
    <fullName>abd_DRAM_Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dramshop Liability Insurance Carrier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>DRAM shop</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses (DRAM Shop)</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Name_of_River_Lake__c.field-meta.xml
<CustomField>
    <fullName>abd_Name_of_River_Lake__c</fullName>
    <label>Name of River/Lake</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Veterans_Organization__c.field-meta.xml
<CustomField>
    <fullName>abd_Veterans_Organization__c</fullName>
    <label>Veterans Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_PremiseQuestions.cls
public with sharing class DX_PremiseQuestions {
	static String notAnswered = '--None--';

    // get the values from the Account record.  First we have to get the Account record id from the user record of the current user.
    // If we don't get anything back on the first SOQL, then the user is not logged on.  We're going to assume that they timed out, since
    // this should have been executed from an authorized page.
    @AuraEnabled
    public static MUSW__Application2__c getApplication(String objectId){
        
        User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
        // if this fails (user timed out), then we need to 
        if (u == (User)null || u.ContactId == null) return new MUSW__Application2__c();

        if (objectId.left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
            list<MUSW__Application2__c> app = [Select Id,Name,Primary_Lic_Type__c,abd_Square_Footage__c,abd_Bond_Company__c,abd_DRAM_shop__c,abd_Veterans_Organization__c,
        		abd_Non_profit__c,abd_Dues_Member_Number__c,abd_Premises_Vehicle_Type__c,abd_Name_of_River_Lake__c,abd_Occupancy_Explination__c,
        		abd_Sell_Gasoline__c,abd_Occupancy_Over_200__c,abd_Premise_County__c,Square_Footage_Retail_Area__c,
        		(select id, abd_License_Type__c from License_Applications__r)		
        		from MUSW__Application2__c 
        		where ID =:objectId
        		order by Id DESC limit 1];
            if (app.size() == 0)  throw new AuraHandledException('No Application found for id ' + objectId + ' in DX_PremiseQuestions.GetApplication');
            return app[0];
        }
        else if (objectId.left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
            return DX_Utils.CreateAppFromLicense(objectId);
        }
        // safety catch.
        return new MUSW__Application2__c();
    }

	@AuraEnabled
    public static list<Account> getDram(){
    	list<Account> temp = new list<Account>();
    	temp.add(new Account(name='--None--'));
       	for(Account a:[Select Id, Name from Account where Type='DRAM Shop' order by Name]){
       		temp.add(a);	
       	} 
       	return temp;
    }
	
	// Get the list of values for the picklist field and pass them back to the lightning component.
    // Add the -- not answered-- choice as the first value.  If we move to radial buttons, this can all change.
    @AuraEnabled
    public static map<string,string[]> getPicklistValues(){
		map<string,string[]> pickVals = new map<string,string[]>();
        string[] options = new string[]{};
        Schema.DescribeFieldResult fieldResult = MUSW__Application2__c.abd_Bond_Company__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.put('bond',options);
        options = new List<String>();
        fieldResult = MUSW__Application2__c.abd_Premises_Vehicle_Type__c.getDescribe();
        ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.put('pVType',options);
        
        return pickVals;
    }

    // Update the record - called from Lightning component.  The lightning component handles the validation now. 

    @AuraEnabled
    public static String upRecordApex(MUSW__Application2__c application){
        
        try{
        	update application;
        }catch(exception ex){
            return ex.getMessage();
        }
        
        return 'Update Successful';
    }    
}