force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License__c.field-meta.xml
<CustomField>
    <fullName>abd_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_DRAM_Shop__c.field-meta.xml
<CustomField>
    <fullName>abd_DRAM_Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dramshop Liability Insurance Carrier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>DRAM shop</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Licenses (DRAM Shop)</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>License Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Related Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Class__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Class__c</fullName>
    <inlineHelpText>classification or function/business/privilege permitted   And I helped with this!</inlineHelpText>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brewer's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Broker's Permit</fullName>
            </value>
            <value>
                <fullName>Carrier Permit</fullName>
            </value>
            <value>
                <fullName>Charity Beer Wine and Liquor Auction Permit</fullName>
            </value>
            <value>
                <fullName>Class A Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class B Liquor License</fullName>
            </value>
            <value>
                <fullName>Class B Native Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class B Wine Permit</fullName>
            </value>
            <value>
                <fullName>Class C Beer Permit</fullName>
            </value>
            <value>
                <fullName>Class C Liquor License</fullName>
            </value>
            <value>
                <fullName>Class C Native Wine</fullName>
            </value>
            <value>
                <fullName>Class D Liquor License</fullName>
            </value>
            <value>
                <fullName>Class E Liquor License</fullName>
            </value>
            <value>
                <fullName>Direct Shipper License</fullName>
            </value>
            <value>
                <fullName>Distiller's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>High Proof Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>High Proof Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Liquor Manufacturer</fullName>
            </value>
            <value>
                <fullName>Micro-Distilled Spirits Permit</fullName>
            </value>
            <value>
                <fullName>Native Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Native Wine Manufacturer</fullName>
            </value>
            <value>
                <fullName>Special Class C Liquor</fullName>
            </value>
            <value>
                <fullName>Vintner's Certificate of Compliance</fullName>
            </value>
            <value>
                <fullName>Wholesale Beer Distributor</fullName>
            </value>
            <value>
                <fullName>Wholesale Wine Distributor</fullName>
            </value>
            <value>
                <fullName>Brew Pub</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>High Proof Brew Pub</fullName>
            </value>
            <value>
                <fullName>Living Quarters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Primary_Licensee__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Primary_Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the help text for the Primary Licensee</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>License2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Timely Filed</fullName>
            </value>
            <value>
                <fullName>In Appeal</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License__c/MUSW__License__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License DO NOT USE</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses DO NOT USE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License__c/fields/MUSW__Class__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Class__c</fullName>
    <inlineHelpText>classification or function/business/privilege permitted</inlineHelpText>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Liquor</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Operation</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License__c/fields/MUSW__Primary_Licensee__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Primary_Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_LicenseListController.cls
public class DX_LicenseListController {
	
	@AuraEnabled
    public static List<licenseListEntry> getLicensesForAccount(Id accountId) {

        list<licenseListEntry> llelist = new list<licenseListEntry>();      // our returned object
        // Go get the license information
        for (MUSW__License2__c tle : [SELECT Id,Name, abd_Effective_Date__c,MUSW__Description__c,MUSW__Class__c, MUSW__Status__c, LastModifiedBy.Name, MUSW__Primary_Licensee__r.Name, MUSW__Primary_Licensee__r.Id FROM MUSW__License2__c where MUSW__Primary_Licensee__c=:accountId ORDER BY createdDate DESC]) {
            licenseListEntry llitem = new licenseListEntry();
            llitem.Lic_Id = tle.Id;
            llitem.Lic_Name = tle.Name;
            llitem.Lic_Class = tle.MUSW__Class__c;
            llitem.Lic_Status = tle.MUSW__Status__c;
            llitem.Lic_LastModifiedBy_Name = tle.LastModifiedBy.Name;
            llitem.Lic_Effective_Date = tle.abd_Effective_Date__c.format();
            llitem.Lic_Description = tle.MUSW__Description__c;
            llitem.Account_Name = tle.MUSW__Primary_Licensee__r.Name;
            llitem.Account_Id = tle.MUSW__Primary_Licensee__r.Id;
            llelist.add(llitem);
        }
        // 
        return llelist;
	
	}
    // Used by ApplicationtoAppeal object
	@AuraEnabled
    public static List<MUSW__License2__c> getLicensesByPrimary(Id licenseId) {
        
        list<MUSW__License2__c> tempList = new list<MUSW__License2__c>();
        try{
        	MUSW__License2__c l = [Select MUSW__Class__c, MUSW__Status__c, LastModifiedBy.Name, 
					        		(Select MUSW__Class__c, MUSW__Status__c, LastModifiedBy.Name From Licenses__r) 
					        		From MUSW__License2__c 
					        		where id = :licenseId];
			templist.add(l)	;	        		
            for(MUSW__License2__c cl:l.Licenses__r){
        		templist.add(cl);		
        	}
           	if(test.isRunningTest() && tempList.size()==0)
           		MUSW__License2__c test = tempList[0];	
        }catch(exception e){}
        
        return tempList;
	
	}
    // Used by ReviewApplication object
	@AuraEnabled
    public static List<license> getLicensesByApplication(Id appId) {
        set<Id> si = new set<Id>();
        for(abd_License_Application__c la:[Select abd_License__c from abd_License_Application__c where abd_Application__c=:appId]){
        	si.add(la.abd_License__c);	
        }
        list<license> tempList = new list<license>();
        try{
        	for(MUSW__License2__c l:[Select Id, MUSW__Class__c, MUSW__Status__c From MUSW__License2__c where Id IN:si]){
		    	tempList.add(new license(l));
		    }
			if(test.isRunningTest() && tempList.size()==0)
           		license test = tempList[0];	
        }catch(exception e){}
        
        return tempList;
	
	}
    // Used by LicenselistItem object
	@AuraEnabled
    public static MUSW__License2__c setAppeal(MUSW__License2__c license) {
        
        license.MUSW__Status__c = 'In Appeal';
        try{
            update license;
            return license;	
        }catch(exception e){}
        
        return null;
	
	}

	
    public class licenseListEntry {
        @AuraEnabled String Lic_Id {get;set;}
        @AuraEnabled String Lic_Name {get;set;}
        @AuraEnabled String Lic_Class {get;set;}
        @AuraEnabled String Lic_Status {get;set;}
        @AuraEnabled String Lic_LastModifiedBy_Name {get;set;}
        @AuraEnabled String Lic_Effective_Date {get;set;}
        @AuraEnabled String Lic_Description {get;set;}
        @AuraEnabled String Account_Name {get;set;}
        @AuraEnabled String Account_Id  {get;set;}
    }
    
    public class license{
    	
    	@AuraEnabled MUSW__License2__c lic {get;set;}
    	@AuraEnabled boolean approved {get;set;}
    	
    	public license(MUSW__License2__c l){
    		this.lic = l;
    		this.approved = false;
    	}	
    }
}