force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_Length__c.field-meta.xml
<CustomField>
    <fullName>abd_Length__c</fullName>
    <formula>text(abd_License__r.abd_Length__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Length</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <formula>text(abd_License__r.abd_License_Type__c )</formula>
    <label>License_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_License_Types__c/abd_License_Types__c.object-meta.xml
<CustomObject>
    <label>License Type</label>
    <nameField>
        <displayFormat>LT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Types__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Effective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_End_Date__c</fullName>
    <inlineHelpText>Last day the policy is effective</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Length__c.field-meta.xml
<CustomField>
    <fullName>abd_Length__c</fullName>
    <inlineHelpText>License Duration, 8 month, 12 month, etc.</inlineHelpText>
    <label>Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Other_Criteria__c.field-meta.xml
<CustomField>
    <fullName>abd_Other_Criteria__c</fullName>
    <label>Other Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Club has more than 250 members</fullName>
            </value>
            <value>
                <fullName>Club has less than 250 members</fullName>
            </value>
            <value>
                <fullName>Veteran’s organization open one day per week or 52 days or less per year</fullName>
            </value>
            <value>
                <fullName>Boat</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Plane</fullName>
            </value>
            <value>
                <fullName>Sells Gas</fullName>
            </value>
            <value>
                <fullName>No Gas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Portal_Processed__c.field-meta.xml
<CustomField>
    <fullName>abd_Portal_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Square_Footage__c.field-meta.xml
<CustomField>
    <fullName>abd_Square_Footage__c</fullName>
    <label>Square Footage Building Interior</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Planning Applications</relationshipLabel>
    <relationshipName>Application2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>DRAM Review</fullName>
            </value>
            <value>
                <fullName>Local Authority Review</fullName>
            </value>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 1 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 2 Review</fullName>
            </value>
            <value>
                <fullName>ABD Level 3 Review</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/Square_Footage_Retail_Area__c.field-meta.xml
<CustomField>
    <fullName>Square_Footage_Retail_Area__c</fullName>
    <label>Square Footage Retail Area</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Active_Status__c.field-meta.xml
<CustomField>
    <fullName>abd_Active_Status__c</fullName>
    <formula>If(AND( abd_Effective_Date__c&lt;=Today(), abd_Effective_End_Date__c  >=Today()),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_Date__c</fullName>
    <label>License Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Effective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>abd_Effective_End_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Length__c.field-meta.xml
<CustomField>
    <fullName>abd_Length__c</fullName>
    <label>Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Length</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_LicenseType__c.field-meta.xml
<CustomField>
    <fullName>abd_LicenseType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License Typel</label>
    <referenceTo>abd_License_Types__c</referenceTo>
    <relationshipLabel>Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Licenses (Primary Contact)</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Primary_License__c.field-meta.xml
<CustomField>
    <fullName>abd_Primary_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary License/Permit</label>
    <referenceTo>MUSW__License2__c</referenceTo>
    <relationshipLabel>Related Licenses</relationshipLabel>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Square_Footage_Retail_Area__c.field-meta.xml
<CustomField>
    <fullName>abd_Square_Footage_Retail_Area__c</fullName>
    <label>Square Footage Retail Area</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>License2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Primary_Licensee__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Primary_Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the help text for the Primary Licensee</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>License2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Timely Filed</fullName>
            </value>
            <value>
                <fullName>In Appeal</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License__c/MUSW__License__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License DO NOT USE</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses DO NOT USE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <inlineHelpText>Person applying for license on behalf of licensee as indicated in Subject</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MUSW__License__c/fields/MUSW__Primary_Licensee__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Primary_Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License__c/fields/MUSW__Status__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_AddPrivilegeApplication.cls
public without sharing class DX_AddPrivilegeApplication {

    static final string NONE = '--None--';

    //Method for DX_AddPrivilegeApplication

    // Because the ADD privilege has NO application questions that need to appear on the application screen, we DON'T have to 
    // insert the app record at this time. (No questions/answers need to be associated to the new application).
    @AuraEnabled
    public static ApplicationAddInit getInfo(String recordId){
        
		try{
			
			MUSW__Application2__c app;
			Boolean isApplication = false;
			list<MUSW__License2__c> relatedLicenses = new list<MUSW__License2__c>();	// Already existing on the license.
			list<abd_License_Application__c> optionalLicenses = new list<abd_License_Application__c>();	// Already selected as "desired" for this license.
			// If they pass us a license ID, then we are coming in for the first time
			if (recordId.left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
			    list<MUSW__License2__c> liclist = [Select abd_License_Type__c, MUSW__Primary_Licensee__c, MUSW__Applicant__r.Id,abd_Length__c,
			    		    abd_Other_Criteria__c, abd_Square_Footage_Retail_Area__c,abd_Square_Footage__c, abd_Effective_Date__c, abd_Effective_End_Date__c,
			        		(Select Id, abd_License_Type__c From Licenses__r where abd_Active_Status__c=true) 
			        		From MUSW__License2__c where id = :recordId];

			    // if it's no good, then just leave.
			    if (liclist.size() <= 0) {
			    	throw new AuraHandledException('No license found with the ID of ' + recordId);
			    	return null;
			    }
			    
			    app = new MUSW__Application2__c();
				MUSW__License2__c primaryLicense = liclist[0];
				relatedLicenses = primaryLicense.Licenses__r;
				System.debug('Primary license ' + primaryLicense);

	            app.name='System Number';
	            app.MUSW__Status__c='Pending';
				app.abd_Portal_Processed__c = true;		    
				app.abd_Primary_License__c = primaryLicense.Id;
			    app.abd_Length__c = primaryLicense.abd_Length__c;
			    app.abd_Square_Footage__c = primaryLicense.abd_Square_Footage__c;
			    app.Square_Footage_Retail_Area__c = primaryLicense.abd_Square_Footage_Retail_Area__c;
			    app.abd_PortalWork_LicenseType__c = primaryLicense.abd_License_Type__c;
			    app.abd_Effective_Date_of_Current_License__c = primaryLicense.abd_Effective_Date__c;
			    app.abd_Effective_End_Date_of_Current_Lic__c = primaryLicense.abd_Effective_End_Date__c;
			    app.abd_Effective_Date__c = null;
			    app.abd_Effective_End_Date__c = null;
			    app.abd_Temporary_or_Permanent__c = 'Permanent';
			    app.MUSW__Account__c = primaryLicense.MUSW__Primary_Licensee__c;
			    app.MUSW__Applicant__c = primaryLicense.MUSW__Applicant__r.Id;
			    app.RecordTypeId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Add Privilege or License to Existing License').getRecordTypeId();
			}

			// If it's an existing application, it gets a little more complicated.
			// Get the record and fields
			// Get the related - already existing licenses
			// Get the related - optional - previously selected licenses.
			if (recordId.left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
				list<MUSW__Application2__c> applist = [Select Id, MUSW__Status__c, abd_Portal_Processed__c, abd_Primary_License__c, 
						abd_Length__c, abd_Square_Footage__c, Square_Footage_Retail_Area__c, abd_PortalWork_LicenseType__c, 
						abd_Effective_Date_of_Current_License__c, abd_Effective_End_Date_of_Current_Lic__c, abd_Effective_Date__c, 
						abd_Effective_End_Date__c, abd_Temporary_or_Permanent__c, MUSW__Account__c, MUSW__Applicant__c, RecordTypeId, 
						MUSW__Description__c, abd_Outdoor_Service_Area_Boundary_Info__c
						From MUSW__Application2__c a where ID = :recordId];

			    // if it's no good, then just leave.
			    if (applist.size() <= 0) {
			    	throw new AuraHandledException('No application found with the ID of ' + recordId);
			    	return null;
			    }
			    
			    isApplication = true;
			    app = applist[0];
			    relatedLicenses = [Select Id, abd_License_Type__c From MUSW__License2__c where abd_Active_Status__c=true and 
										abd_Primary_License__c = :app.abd_Primary_License__c];
				optionalLicenses = [Select Id, abd_License_Type__c From abd_License_Application__c where abd_Application__c = :app.Id];
			}

		    // So we have a license and all of the related license records.  Let's go get a list of what is available
		    list<abd_License_Types__c> possibleLicList = DX_Utils.GetQualifiedLicenseTypes(app.abd_Length__c);

       		// convert the list of existing add ons into a set
	        set<String> selectedLicTypes = new set<String>();
	        for (integer i = 0; i < optionalLicenses.size(); i++) {
	        	selectedLicTypes.add(optionalLicenses[i].abd_License_Type__c);
	        }

       		// convert the list of selected optional add ons into a set
	        set<String> existingLicTypes = new set<String>();
	        for (integer i = 0; i < relatedLicenses.size(); i++) {
	        	existingLicTypes.add(relatedLicenses[i].abd_License_Type__c);
	        }

	        // so now, we go through the list of license types that they could add, and seperate them into three piles
	        // what they have (existing), what is optional.  There shouldn't ever be any more requireds
	        // 

           	abd_License_Types__c primary = new abd_License_Types__c();
        	map<string,abd_License_Types__c> lmap = new map<string,abd_License_Types__c>();

        	// start to build out the licenseTypes structure to return 
            DX_Utils.LicenseTypeStructure licTypeStruct = new DX_Utils.LicenseTypeStructure(primary);

        	// first build a map of the license type records and copy the primary and existing records when we see them.
            for(abd_License_Types__c ltype:possibleLicList){
            	lmap.put(ltype.abd_License_Type__c,ltype);
            	// Quick check for the primary license type record
            	if(app.abd_PortalWork_LicenseType__c == ltype.abd_License_Type__c)
            		primary = ltype;   
            	//and if these exist on the license, then add them to the existing set
	            if (existingLicTypes.contains(ltype.abd_License_Type__c))
	            	if (ltype.Type_Of_Add_On__c == 'Sublicense' || ltype.Type_Of_Add_On__c == 'Permit')
		            	licTypeStruct.existingSLP.add(new DX_Utils.LicenseType(true,false,true,ltype));	
		            else if (ltype.Type_Of_Add_On__c == 'Privilege') 
		            	licTypeStruct.existingPrv.add(new DX_Utils.LicenseType(true,false,true,ltype));	

	        }

	        // get the list of optionals - should have all mandatory and most included license types
            string opt = primary.Optional_Add_On_Privileges__c;
            if(app.abd_Length__c=='12 months'){
            	opt+=(';'+primary.Optional_12Mo_Add_Ons_Privileges__c);	
            }else{
            	opt+=(';'+primary.Optional_Not_12Mo_Add_Ons_Privileges__c);
            }
            if(opt!=null){
	            for(string s:opt.split(';')){
	            	// no blanks, must exist in the list of valid choices and not already exist
	            	if(s != '' && lmap.containsKey(s) && !existingLicTypes.contains(s)) {
	            		if (s == 'WBN' && (existingLicTypes.contains('WB') ||  existingLicTypes.contains('WCN') ||
	            							selectedLicTypes.contains('WB') || selectedLicTypes.contains('WCN')))
	            			continue;
	            		if ((s == 'WB' || s == 'WCN') && (existingLicTypes.contains('WBN') || selectedLicTypes.contains('WBN')))
	            			continue;
	            		Boolean selected = selectedLicTypes.contains(s);
		            	if (lmap.get(s).Type_Of_Add_On__c == 'Sublicense' || lmap.get(s).Type_Of_Add_On__c == 'Permit')
				            	licTypeStruct.optionalSLP.add(new DX_Utils.LicenseType(selected,false,isApplication,lmap.get(s)));	
			            else if (lmap.get(s).Type_Of_Add_On__c == 'Privilege') 
				            	licTypeStruct.optionalPrv.add(new DX_Utils.LicenseType(selected,false,isApplication,lmap.get(s)));	
	            	}
	            }
            }


            // Since the user could have unselected an included option, we have to show these again.
            // But let's add these to the optional list now, since they aren't mandatory.
            if(primary.Included_Add_On_Privileges__c!=null){
	            for(string s:primary.Included_Add_On_Privileges__c.split(';')){
	            	if(s!='' && lmap.containsKey(s) && !existingLicTypes.contains(s))
		            	if (lmap.get(s).Type_Of_Add_On__c == 'Sublicense' || lmap.get(s).Type_Of_Add_On__c == 'Permit')
			            	licTypeStruct.optionalSLP.add(new DX_Utils.LicenseType(true,false,isApplication,lmap.get(s)));	
			            else if (lmap.get(s).Type_Of_Add_On__c == 'Privilege') 
			            	licTypeStruct.optionalPrv.add(new DX_Utils.LicenseType(true,false,isApplication,lmap.get(s)));	

	            }
            }
            if (primary.Included_Not_12Mo_Add_Ons_Privileges__c != null && (app.abd_Length__c !='12 months')) {
             for(string s:primary.Included_Not_12Mo_Add_Ons_Privileges__c.split(';')){
                    if(s!='' && lmap.containsKey(s) && !existingLicTypes.contains(s))
		            	if (lmap.get(s).Type_Of_Add_On__c == 'Sublicense' || lmap.get(s).Type_Of_Add_On__c == 'Permit')
			            	licTypeStruct.optionalSLP.add(new DX_Utils.LicenseType(true,false,isApplication,lmap.get(s)));	
			            else if (lmap.get(s).Type_Of_Add_On__c == 'Privilege') 
			            	licTypeStruct.optionalPrv.add(new DX_Utils.LicenseType(true,false,isApplication,lmap.get(s)));	

                }   
            }

            // I think we're all done, so let's build the container object to pass back to JS

            return new ApplicationAddInit (app, licTypeStruct);


        }catch (Exception ex) {
        	system.debug(ex.getMessage() + ex.getStackTraceString());
        	throw new AuraHandledException(ex.getMessage() + ex.getStackTraceString());
        }
    }
    
	//Method for DX_AddPrivilegeApplication
    @AuraEnabled
    public static string createAddApp(string lts, MUSW__Application2__c app,string os){
        Savepoint sp = Database.setSavepoint();
        try{
            User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
            if(u.ContactId==null){
                throw new AuraHandledException ('It looks like you are no longer logged in to the system.  Unable to save the information');
                return null;
            }

            // Build a list of all of the selected options 
			DX_Utils.LicenseTypeStructure lTypes = (DX_Utils.LicenseTypeStructure) JSON.deserializeStrict(lts,DX_Utils.LicenseTypeStructure.class);
            list<DX_Utils.LicenseType> llt = new list<DX_Utils.LicenseType>();
            llt.addAll(lTypes.optionalSLP);
            llt.addAll(lTypes.optionalPrv);
            list<MUSW__License2__c> licenses = new list<MUSW__License2__c>();


            // LICENSE OBJECT - for everything they selected for options.
            for(DX_Utils.LicenseType lt:llt){
            	if(lt.selected){
	            	MUSW__License2__c lic = new MUSW__License2__c();
	            	lic.MUSW__Applicant__c = app.MUSW__Applicant__r.Id;
	            	lic.name='System Number';
	            	lic.MUSW__Class__c = lt.ltype.abd_Class__c;
	            	lic.abd_License_Type__c = lt.ltype.abd_License_Type__c;
	            	licenses.add(lic);
            	}   
            }
            insert licenses;

            // APPLICATION OBJECT - built early and passed around before we actually write it out.
			app.abd_Outdoor_Service_Area_Boundary_Info__c=os;
			system.debug(app);
            insert app;

            // LICENSE APPLICATION OBJECTS (one per each license record added)
            list<abd_License_Application__c> lla = new list<abd_License_Application__c>();
            for(MUSW__License2__c l:licenses){
            	lla.add(new abd_License_Application__c(abd_Application__c=app.Id,abd_License__c=l.Id,abd_Primary_License__c=false,abd_Application_Status__c='Pending',abd_Portal_Processed__c = true));
            }
            insert lla;


            return 'SUCCESS: ' + String.valueOf(app.Id);
        }catch (Exception ex) {
            Database.rollback(sp);
            System.debug(ex.getMessage() + ex.getStackTraceString());
        	throw new AuraHandledException(ex.getMessage() + ex.getStackTraceString());
        }
    }

    // WE need to manage moving from a pending to in progress state to get the DRE rules to fire.
 	@AuraEnabled
    public static void updateLicenseApplicationRecords(Id appId ){
    	try {
	    	list<abd_License_Application__c> lla = [Select ID, abd_Application_Status__c from abd_License_Application__c where abd_Application__c=:appId];
	    	if (lla.size() > 0) {
	    		for (abd_License_Application__c la : lla) {
	    			la.abd_Application_Status__c = 'In Progress';
	    		}
	    		
	    		// update them all
	    		update lla;
	    	}
    	} catch (Exception ex) {
    		throw new AuraHandledException (ex.getMessage() + ex.getStackTraceString());
    	}
    }
	   
 
    @AuraEnabled
    public static string getFeeSchedule(string appInfo){
	        return DX_Utils.getFeeSchedule(appInfo);
    }
    
    public class ApplicationAddInit{

		@AuraEnabled public MUSW__Application2__c app {get;set;}
		@AuraEnabled public DX_Utils.LicenseTypeStructure licTypeList {get;set;}

		public ApplicationAddInit(MUSW__Application2__c app, DX_Utils.LicenseTypeStructure licTypeList) {
			this.app = app;        // a license object to return
			this.licTypeList = licTypeList;
		}
		

	}
}