force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <formula>text(abd_License__r.abd_License_Type__c )</formula>
    <label>License_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_License_Types__c/abd_License_Types__c.object-meta.xml
<CustomObject>
    <label>License Type</label>
    <nameField>
        <displayFormat>LT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Types__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/abd_License_Types__c/fields/PremisesMustBeIowa__c.field-meta.xml
<CustomField>
    <fullName>PremisesMustBeIowa__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, the premises must exist in Iowa</description>
    <label>PremisesMustBeIowa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/abd_Account_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>abd_Account_Email_Address__c</fullName>
    <label>Account Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/abd_Corporate_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>abd_Corporate_ID_Number__c</fullName>
    <inlineHelpText>Business number assigned by Secretary of State of Iowa</inlineHelpText>
    <label>Business ID Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/abd_DBA__c.field-meta.xml
<CustomField>
    <fullName>abd_DBA__c</fullName>
    <label>DBA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Liability Company</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Municipality</fullName>
            </value>
            <value>
                <fullName>Non-profit Association</fullName>
            </value>
            <value>
                <fullName>Privately-Held Corporation</fullName>
            </value>
            <value>
                <fullName>Publicly Traded Corporation</fullName>
            </value>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>Foreign corporation as defined in section 504.141</fullName>
                <isActive>false</isActive>
                <label>Foreign corporation as defined in section 504.141</label>
            </value>
            <value>
                <fullName>Nonprofit corporation organized under chapter 504</fullName>
                <isActive>false</isActive>
                <label>Nonprofit corporation organized under chapter 504</label>
            </value>
            <value>
                <fullName>Nonprofit entity which has a principal office in the State of Iowa</fullName>
                <isActive>false</isActive>
                <label>Nonprofit entity which has a principal office in the State of Iowa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Corporate_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>abd_Corporate_ID_Number__c</fullName>
    <label>Corporate ID Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_DBA__c.field-meta.xml
<CustomField>
    <fullName>abd_DBA__c</fullName>
    <inlineHelpText>Business name</inlineHelpText>
    <label>Doing Business As</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Other_Criteria__c.field-meta.xml
<CustomField>
    <fullName>abd_Other_Criteria__c</fullName>
    <label>Other Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Club has more than 250 members</fullName>
            </value>
            <value>
                <fullName>Club has less than 250 members</fullName>
            </value>
            <value>
                <fullName>Veteran’s organization open one day per week or 52 days or less per year</fullName>
            </value>
            <value>
                <fullName>Boat</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Plane</fullName>
            </value>
            <value>
                <fullName>Sells Gas</fullName>
            </value>
            <value>
                <fullName>No Gas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_Address__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Address__c</fullName>
    <inlineHelpText>Address of location to be licensed</inlineHelpText>
    <label>Premises Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_State__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_State__c</fullName>
    <label>Premises State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/abd_Premise_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Zip_Code__c</fullName>
    <label>Premises Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Account__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Planning Applications</relationshipLabel>
    <relationshipName>Application2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/fields/Primary_Lic_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Lic_Type__c</fullName>
    <formula>TEXT(abd_Primary_License__r.abd_License_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary_Lic_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_DBA__c.field-meta.xml
<CustomField>
    <fullName>abd_DBA__c</fullName>
    <label>DBA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Premise_Address__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_Address__c</fullName>
    <label>Premises Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/abd_Premise_City__c.field-meta.xml
<CustomField>
    <fullName>abd_Premise_City__c</fullName>
    <label>Premises City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Applicant__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>License2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MUSW__License2__c/fields/MUSW__Primary_Licensee__c.field-meta.xml
<CustomField>
    <fullName>MUSW__Primary_Licensee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the help text for the Primary Licensee</inlineHelpText>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>License2s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DX_LicenseeForm.cls
public without sharing class DX_LicenseeForm {
    static String notAnswered = '--None--';

    // get the values from the Account record.  First we have to get the Account record id from the user record of the current user.
    // If we don't get anything back on the first SOQL, then the user is not logged on.  We're going to assume that they timed out, since
    // this should have been executed from an authorized page.
    @AuraEnabled
    public static Account getAccount(String appId){
        
        User u = [Select Contact.AccountId From User Where Id = :UserInfo.getUserId()];

        // if this fails (user timed out), then we need to 
        if (u == (User)null || u.ContactId == null || u.Contact.AccountId == null) return new Account();

        list<Account> a = new list<Account>();
        if (String.valueOf(appId).left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
            a = [Select Id,Name, Phone,Business_Type__c,BillingStreet,BillingCity,BillingState,BillingPostalCode,abd_Corporate_ID_Number__c,abd_Account_Email_Address__c,abd_DBA__c from Account 
                        where Id in (select MUSW__Account__c from MUSW__Application2__c where ID =: appId)];
            }
        else 
        if (String.valueOf(appId).left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
            a = [Select Id,Name, Phone,Business_Type__c,BillingStreet,BillingCity,BillingState,BillingPostalCode,abd_Corporate_ID_Number__c,abd_Account_Email_Address__c,abd_DBA__c from Account 
                        where Id in (select MUSW__Primary_Licensee__c from MUSW__License2__c where ID =: appId) limit 1];
            }



        // if (String.isEmpty(a.Name)) a.Name = ' ';
        // if (String.isEmpty(a.Phone)) a.Phone = ' ';
        // if (String.isEmpty(a.BillingStreet)) a.BillingStreet = ' ';
        // if (String.isEmpty(a.BillingCity)) a.BillingCity = ' ';
        // if (String.isEmpty(a.BillingState)) a.BillingState = ' ';
        // if (String.isEmpty(a.BillingPostalCode)) a.BillingPostalCode = ' ';
        // if (String.isEmpty(a.abd_Corporate_ID_Number__c)) a.abd_Corporate_ID_Number__c = ' ';
        // if (String.isEmpty(a.abd_Account_Email_Address__c)) a.abd_Account_Email_Address__c = ' ';
        // if (String.isEmpty(a.abd_DBA__c)) a.abd_DBA__c = ' ';

        if (a.size() > 0)
            return a[0];
        else
            throw new AuraHandledException('No related Licensee (Account) record found for the record Id Provided ' + appId);
    }
	// get the values from the contact record.  First we have to get the contact record id from the user record of the current user.
    // If we don't get anything back on the first SOQL, then the user is not logged on.  We're going to assume that they timed out, since
    // this should have been executed from an authorized page.

    // appId could point to an application or a license.  First look to see if the applicant is set on either of those objects
    // If not, then we use the current user.
    @AuraEnabled
    public static Contact getContact(String appId){
        
        Id pc;
        if (String.valueOf(appId).left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
            list<MUSW__Application2__c> alist = [Select MUSW__Applicant__c from MUSW__Application2__c where Id = :appid limit 1];
            if (alist.size() > 0) 
                pc = alist[0].MUSW__Applicant__c;
        }
        if (String.valueOf(appId).left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
            list<MUSW__License2__c> llist = [Select MUSW__Applicant__c from MUSW__License2__c where Id = :appid limit 1];
            if (llist.size() > 0) 
                pc = llist[0].MUSW__Applicant__c;
        }

        list<Contact> c = new list<Contact>();
        if (pc != null) {
            c = [Select Id, Phone,Email,FirstName,LastName from Contact where Id = :pc];
        }
        else 
        {            
            User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
            // if this fails (user timed out), then we need to 
            if (u != (User)null && u.ContactId != (Id)null) 
                c = [Select Id, Phone,Email,FirstName,LastName from Contact where Id=:u.ContactId];
        }
        
        // // remove this once the locker service is fixed to handle null values on the client side correctly.
        // if (String.isEmpty(c.Email)) c.Email = ' ';
        // if (String.isEmpty(c.MobilePhone)) c.MobilePhone = ' ';
        // if (String.isEmpty(c.FirstName)) c.FirstName = ' ';
        // if (String.isEmpty(c.LastName)) c.LastName = ' ';

        if (c.size() > 0)
            return c[0];
        else
            throw new AuraHandledException('No related Applicant (contact) record found for the record Id Provided ' + appId);

    }
    // Get the list of values for the picklist field and pass them back to the lightning component.
    // Add the -- not answered-- choice as the first value.  If we move to radial buttons, this can all change.
    @AuraEnabled
    public static map<string,string[]> getPicklistValues(Id objectId){
		map<string,string[]> pickVals = new map<string,string[]>();
        string[] options = new string[]{};
        Schema.DescribeFieldResult fieldResult = MUSW__Application2__c.abd_Premise_State__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        pickVals.put('state',options);

        // for business types - Don't include municipality if this is an out of state license.

        Boolean showMunicip = true;
      
        list<MUSW__Application2__c> ooslist = [Select id, Primary_Lic_Type__c from  MUSW__Application2__c where Id = :objectId];
        if (ooslist.size() > 0) {
            String primLicenseType = ooslist[0].Primary_Lic_Type__c;
            list<abd_License_Types__c> ltlist = [Select abd_License_Type__c from abd_License_Types__c where PremisesMustBeIowa__c = false and abd_License_Type__c = :primLicenseType ];
            if (ltlist.size() > 0)
                showMunicip = false;
        }

        options = new List<String>();
        fieldResult = Account.Business_Type__c.getDescribe();
        ple = fieldResult.getPicklistValues();
            options.add(notAnswered);
        for (Schema.PicklistEntry f: ple) {
            if (f.getLabel() != 'Municipality')
                options.add(f.getLabel());
            else
                if (showMunicip)
                    options.add(f.getLabel());

        }
        pickVals.put('bType',options);
        return pickVals;
    }

    // Update the record - called from Lightning component.  The lightning component handles the validation now. 

    @AuraEnabled
    public static String upRecordApex(Account licensee,Contact applicant){
        
        try{
        	update applicant;
            update licensee;
        }catch(exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
        
        return 'Update Successful';
    }
    // Get the current application 
    @AuraEnabled
    public static MUSW__Application2__c getApplication(String objectId){
        
        User u = [Select ContactId From User Where Id = :UserInfo.getUserId()];
        // if this fails (user timed out), then we need to 
        //if (u == (User)null || u.ContactId == null) return new MUSW__Application2__c();
        if (objectId.left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
            list<MUSW__Application2__c> app =  [Select Id,Name,abd_Other_Criteria__c,abd_Premise_Address__c,abd_Premise_City__c,abd_Premise_State__c,
                abd_Premise_Zip_Code__c,abd_Premise_County__c,Premises_Type__c,abd_Temporary_or_Permanent__c,
                abd_Effective_Date__c,abd_Effective_End_Date__c,abd_Local_Authority__c,abd_Square_Footage__c,
                abd_Outdoor_Service_Area_Boundary_Info__c,Primary_Lic_Type__c,abd_Available_as_temporary_license__c,
                abd_Outdoor_Service_Endorsement__c,abd_Time_of_Auction_Beginning__c,
                abd_Time_of_Auction_Ending__c,abd_Use_Mailing__c,abd_DBA__c,abd_Premise_Address_2__c, abd_Local_Authority_Type__c,
                CreatedDate, abd_Charity_Business_Type__c, 
                (select id, abd_License_Type__c from License_Applications__r)
                from MUSW__Application2__c 
                where Id = :objectId
                order by Id DESC limit 1];
            if (app.size() == 0) throw new AuraHandledException('No records returned from Get Application in DX_Licensee Apex');
            return app[0];
        }
        else if (objectId.left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
            return DX_Utils.CreateAppFromLicense(objectId);
        }
        // Safety code we should never hit.
        return new MUSW__Application2__c();       
    }




    // There are lots of reasons why something isn't a new application, so it's a failure unless proven wrong.
    @AuraEnabled
    public static boolean isNewApplication(String appId){
        Boolean answer = false;
        try{
            if (String.valueOf(appId).left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
                List<MUSW__Application2__c> al = [Select recordType.Name from MUSW__Application2__c where Id = :appid limit 1];
                if (al.size() > 0) {
                    String rtn = al[0].recordType.Name;
                    answer = (rtn == 'New Application' || rtn == 'Auction Application' || rtn == 'Keg Registration') ;
                }
            }
        }
        finally{}
        
        return answer;
    }
}