force-app/main/default/objects/abd_License_Application__c/abd_License_Application__c.object-meta.xml
<CustomObject>
    <description>Junction object of License &amp; Application records</description>
    <label>License-Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License-Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Application__c/fields/abd_Application__c.field-meta.xml
<CustomField>
    <fullName>abd_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>MUSW__Application2__c</referenceTo>
    <relationshipLabel>License-Applications</relationshipLabel>
    <relationshipName>License_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/abd_License_Application__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <formula>text(abd_License__r.abd_License_Type__c )</formula>
    <label>License_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/abd_License_Types__c/abd_License_Types__c.object-meta.xml
<CustomObject>
    <label>License Type</label>
    <nameField>
        <displayFormat>LT-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/abd_License_Types__c/fields/abd_Available_Actions__c.field-meta.xml
<CustomField>
    <fullName>abd_Available_Actions__c</fullName>
    <description>The API name of the entries MUST align with the values in the dx_IconManagement_mdt metadata object</description>
    <label>Available Actions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AdditionalLocations</fullName>
                <label>Additional Locations</label>
            </value>
            <value>
                <fullName>AddPrivilege</fullName>
                <label>Add Privilege</label>
            </value>
            <value>
                <fullName>Appeal</fullName>
            </value>
            <value>
                <fullName>ChangeDramCarrier</fullName>
                <label>Change Dram Carrier</label>
            </value>
            <value>
                <fullName>LabelApproval</fullName>
                <label>Label Approval</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>KegRegistrationBooklet</fullName>
                <label>Order Keg Registration booklet</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Renew</fullName>
            </value>
            <value>
                <fullName>TransferLicense</fullName>
                <label>Transfer a License</label>
            </value>
            <value>
                <fullName>UpdateOfficer</fullName>
                <label>Update Officer</label>
            </value>
            <value>
                <fullName>UpdateOwner</fullName>
                <label>Update Owner</label>
            </value>
            <value>
                <fullName>UpdatePremises</fullName>
                <label>Update Premises</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/abd_License_Types__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/dx_IconManagement__mdt/dx_IconManagement__mdt.object-meta.xml
<CustomObject>
    <description>Holds information about an icon, the text to display, alt text, and navigation link</description>
    <label>dx_IconManagement</label>
    <pluralLabel>dx_IconManagement</pluralLabel>
</CustomObject>

force-app/main/default/objects/dx_IconManagement__mdt/fields/AltText__c.field-meta.xml
<CustomField>
    <fullName>AltText__c</fullName>
    <description>Text for Screen readers and when Icons aren't visible</description>
    <label>AltText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_IconManagement__mdt/fields/IconFileName__c.field-meta.xml
<CustomField>
    <fullName>IconFileName__c</fullName>
    <description>Name of the icon in the agreed upon resource file.  The developer dictates the format of this field.   Current standard is to hold the foldername and filename with extension in this field.</description>
    <label>IconFileName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_IconManagement__mdt/fields/Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Page_URL__c</fullName>
    <description>URL of the community page for navigation purposes.  typically, this is the pagename following the /s/ in the community URL</description>
    <label>Page URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/dx_IconManagement__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Holds the title of the icon - This is the hover text for the Icon</description>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/MUSW__License2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MUSW__License2__c/fields/abd_License_Type__c.field-meta.xml
<CustomField>
    <fullName>abd_License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MUSW__Class__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>abd_License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/dx_AvailableActions.cls
public without sharing class dx_AvailableActions {
    
    @AuraEnabled
	public static list<dx_IconManagement__mdt> getAvailbleIcons(String recordId){
		system.debug(recordId);
		list<dx_IconManagement__mdt> imList = new list<dx_IconManagement__mdt>();

		// Null parameters are not allowed.
		if (String.isBlank(recordId)) 
			throw new AuraHandledException('Record Id parameter was null.');
		else {
			list<String> ltlist = new list<String>();
			// If this is an application
			if (recordId.left(3) == Schema.SObjectType.MUSW__Application2__c.getKeyPrefix()) {
				for (abd_License_Application__c la :  [Select abd_License_Type__c from abd_License_Application__c where abd_Application__r.Id = :recordId]) {
					if (!String.isBlank(la.abd_License_Type__c))
						ltlist.add(la.abd_License_Type__c);
				}
			}
			// If this is an license - Only will retreive one row by the way.
 			else if (recordId.left(3) == Schema.SObjectType.MUSW__License2__c.getKeyPrefix()) {
				for (MUSW__License2__c la :  [Select abd_License_Type__c from MUSW__License2__c where Id = :recordId]) {
					if (!String.isBlank(la.abd_License_Type__c))
						ltlist.add(la.abd_License_Type__c);
				}
			}

			if (ltlist.isEmpty())
				throw new AuraHandledException('No license types found for record id: ' + recordId);

			System.debug('ltlist - ' + ltlist);

			list<String> aalist = new list<String>();
			// Get the available actions
			for (abd_License_Types__c lt : [Select abd_Available_Actions__c from abd_License_Types__c where abd_License_Type__c in :ltlist]) {
				if (!String.isBlank(lt.abd_Available_Actions__c))
					aalist.addAll(lt.abd_Available_Actions__c.split(';'));		
			}

			if (aalist.isEmpty())
				throw new AuraHandledException('No available actions exist for license types ' + ltlist + ' on record Id ' + recordId);
			System.debug('aalist - ' + aalist + ' first item ' + aalist[0]);
			imList = [Select DeveloperName, MasterLabel, AltText__c, Title__c, Page_URL__c, IconFileName__c 
											from dx_IconManagement__mdt where DeveloperName in :aalist ];

			// Since we shouldn't even try to display a list for the AC license (which can only be creted), this 
			// should be an error if we get here.  But for UAT1, we need to disable this message.
			//TODO: re-enable these lines after UAT1
			// if (imlist.isEmpty())
				//throw new AuraHandledException('No available icons found for available actions ' + aalist + ' on record id ' + recordId);	

		}
		return imList;
	}

}