force-app/main/default/objects/BGBL__Batch_Letter__c/BGBL__Batch_Letter__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Single and Batch letter configuration</description>
    <label>Letter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Batch_Letter__c/fields/BGBL__Output_Type__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Output_Type__c</fullName>
    <label>Output Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Word 2003 or earlier (.doc)</fullName>
            </value>
            <value>
                <fullName>Word 2007 (.docx)</fullName>
            </value>
            <value>
                <fullName>Acrobat (.pdf)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/BGBL__Batch_Letter_Job__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Letter job stats</description>
    <label>Letter Job</label>
    <nameField>
        <displayFormat>BLJ-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/fields/BGBL__Batch_Letter__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Batch_Letter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Letter</label>
    <referenceTo>BGBL__Batch_Letter__c</referenceTo>
    <relationshipName>Batch_Run_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/fields/BGBL__Child_Iterate_Ids__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Child_Iterate_Ids__c</fullName>
    <inlineHelpText>Record id's to filter children record results further</inlineHelpText>
    <label>Child Iterate Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/fields/BGBL__HasChildIds__c.field-meta.xml
<CustomField>
    <fullName>BGBL__HasChildIds__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasChildIds</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/fields/BGBL__Override_Parameters__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Override_Parameters__c</fullName>
    <label>Override Parameters</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/fields/BGBL__Single_Letter_Job__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Single_Letter_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only one letter in this job</inlineHelpText>
    <label>Single</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/fields/BGBL__Status__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Queue (verifying...)</fullName>
                <default>true</default>
                <label>In Queue (verifying...)</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DREAddLetterHandler.cls
global class DREAddLetterHandler implements DRE.DREInterface.IResultActionHandler
{
    public DRE.DREResultActionOutput execute(DRE.DREResultContext rc)
    {
        DRE.DREResultActionOutput result = new DRE.DREResultActionOutput();
        
        // create Batch Letter record
        SObject letter = Schema.getGlobalDescribe().get('bgbl__batch_letter_job__c').newSObject();
        letter.put('BGBL__Status__c', 'In Queue (verifying...)');
        letter.put('BGBL__Single_Letter_Job__c', true);
        
        // no objects are to be specified for Add Letter so just get the first Scope Record
        DRE.DREResultVO[] results = rc.getScopeRecords()[0].getResults();
        
        String letterName;
        String outputType;
        for (DRE.DREResultVO rvo : results)
        {
            Object value = rvo.getLiteralValue();
            if (rvo.getAttribute() == 'letterName') letterName = (String)value;
            else if (rvo.getAttribute() == 'letterOutputType') outputType = (String)value;
            else if (rvo.getAttribute() == 'letterParentId') letter.put('BGBL__Override_Parameters__c', 'WHERE Id=\'' + (String)value + '\'');
        }
        
        if (letterName == null) throw new DRELetterManager.LetterException('Action attribute Letter Name not specified');
        
        if (outputType == null) outputType = DRELetterManager.getLetterOutputType(letterName);
        Id letterId = DRELetterManager.getLetterId(letterName);
        String childIds = DRELetterManager.getChildrenIds(letterName, rc);
        
        letter.put('BGBL__Output_Type__c', outputType);
        letter.put('BGBL__Batch_Letter__c', letterId);
        letter.put('BGBL__Child_Iterate_Ids__c', childIds);
        letter.put('BGBL__HasChildIds__c', childIds != null);
        
        Set<String> fieldsChanged = new Set<String>{'BGBL__Batch_Letter__c', 'BGBL__Output_Type__c', 'BGBL__Status__c', 'BGBL__Single_Letter_Job__c', 'BGBL__Override_Parameters__c', 'BGBL__Child_Iterate_Ids__c', 'BGBL__HasChildIds__c'};
        result.addRecordForUpsert(DRE.DREObjectFactory.createObject(letter), fieldsChanged);
        
        return result;
    }
}