force-app/main/default/objects/BGBL__Batch_Letter__c/BGBL__Batch_Letter__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Single and Batch letter configuration</description>
    <label>Letter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Batch_Letter__c/fields/BGBL__Output_Type__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Output_Type__c</fullName>
    <label>Output Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Word 2003 or earlier (.doc)</fullName>
            </value>
            <value>
                <fullName>Word 2007 (.docx)</fullName>
            </value>
            <value>
                <fullName>Acrobat (.pdf)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/BGBL__Batch_Letter_Job__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Letter job stats</description>
    <label>Letter Job</label>
    <nameField>
        <displayFormat>BLJ-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGBL__Batch_Letter_Job__c/fields/BGBL__Batch_Letter__c.field-meta.xml
<CustomField>
    <fullName>BGBL__Batch_Letter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch Letter</label>
    <referenceTo>BGBL__Batch_Letter__c</referenceTo>
    <relationshipName>Batch_Run_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRE__DRE_Result__c/DRE__DRE_Result__c.object-meta.xml
<CustomObject>
    <customHelpPage>DRE__DREHelp</customHelpPage>
    <label>DRE Result</label>
    <nameField>
        <displayFormat>DRERSLT-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRE Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRE__DRE_Result__c/fields/DRE__Attribute__c.field-meta.xml
<CustomField>
    <fullName>DRE__Attribute__c</fullName>
    <description>Used to store content (e.g. email)</description>
    <label>Attribute</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRE__DRE_Result__c/fields/DRE__DRE_Group__c.field-meta.xml
<CustomField>
    <fullName>DRE__DRE_Group__c</fullName>
    <label>DRE Result Group</label>
    <referenceTo>DRE__DRE_Result_Group__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>DRE_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DRE__DRE_Result__c/fields/DRE__DRE_Rule__c.field-meta.xml
<CustomField>
    <fullName>DRE__DRE_Rule__c</fullName>
    <label>DRE Rule</label>
    <referenceTo>DRE__DRE_Rule__c</referenceTo>
    <relationshipLabel>Rule Results</relationshipLabel>
    <relationshipName>DRE_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DRE__DRE_Result_Group__c/DRE__DRE_Result_Group__c.object-meta.xml
<CustomObject>
    <customHelpPage>DRE__DREHelp</customHelpPage>
    <label>DRE Result Group</label>
    <nameField>
        <displayFormat>DRERESG-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DRE Result Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRE__DRE_Result_Group__c/fields/DRE__Action_Type__c.field-meta.xml
<CustomField>
    <fullName>DRE__Action_Type__c</fullName>
    <label>Action Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRE__DRE_Result_Group__c/fields/DRE__DRE_Rule__c.field-meta.xml
<CustomField>
    <fullName>DRE__DRE_Rule__c</fullName>
    <label>DRE Rule</label>
    <referenceTo>DRE__DRE_Rule__c</referenceTo>
    <relationshipLabel>Result Groups</relationshipLabel>
    <relationshipName>DRE_Result_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DRE__DRE_Rule__c/DRE__DRE_Rule__c.object-meta.xml
<CustomObject>
    <customHelpPage>DRE__DREHelp</customHelpPage>
    <label>DRE Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRE Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRE__DRE_Rule__c/fields/DRE__Event__c.field-meta.xml
<CustomField>
    <fullName>DRE__Event__c</fullName>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRE__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Edited</fullName>
            </value>
            <value>
                <fullName>Created or Edited</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>However Impacted</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
            <value>
                <fullName>Unit Test Event A</fullName>
            </value>
            <value>
                <fullName>Unit Test Event B</fullName>
            </value>
            <value>
                <fullName>Batched</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRE__DRE_Rule__c/fields/DRE__Order__c.field-meta.xml
<CustomField>
    <fullName>DRE__Order__c</fullName>
    <defaultValue>999</defaultValue>
    <label>Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DRE__DREObjectSettings__c/DRE__DREObjectSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Allows activation/deactivation of DRE for objects</description>
    <label>DRE Object Settings</label>
</CustomObject>

force-app/main/default/objects/DRE__DREObjectSettings__c/fields/DRE__Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>DRE__Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If selected DRE will execute when changes are made to this object</description>
    <inlineHelpText>If selected DRE will execute when changes are made to this object</inlineHelpText>
    <label>Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DRE__DRESettings__c/DRE__DRESettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls behaviour of DRE</description>
    <label>DRE Settings</label>
</CustomObject>

force-app/main/default/objects/MUSW__Application2__c/MUSW__Application2__c.object-meta.xml
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DREAddLetterTest.cls
@isTest
private class DREAddLetterTest
{
    @isTest
    static void addLetter_noChildIterate()
    {
        BGBK.TestMock tm = new BGBK.TestMock();
        
        // create records
        MUSW__Application2__c p = (MUSW__Application2__c)tm.mk('MUSW__Application2__c', new Map<String, Object>{'Name' => 'Test MUSW__Application2__c'});
        tm.mk('bgbl__batch_letter__c', new Map<String, Object>{'Name' => 'Test Letter', 'BGBL__Output_Type__c' => 'Word 2007 (.docx)'});
        
        // create rule
        DRE__DRE_Rule__c r = new DRE__DRE_Rule__c(DRE__Object_Name__c='MUSW__Application2__c', DRE__Event__c='Edited', Name='MUSW__Application2__c edited - Add letter', DRE__Order__c = 999);
        insert r;
        
        DRE__DRE_Result_Group__c rgroupA = new DRE__DRE_Result_Group__c(DRE__Action_Type__c='AddLetter', DRE__DRE_Rule__c=r.Id);
        insert rgroupA;
        DRE__DRE_Result__c rgroupA_result1 = new DRE__DRE_Result__c(DRE__Attribute__c='letterName', DRE__Value__c='Test Letter', DRE__DRE_Group__c=rgroupA.Id, DRE__DRE_Rule__c=r.Id);
        DRE__DRE_Result__c rgroupA_result2 = new DRE__DRE_Result__c(DRE__Attribute__c='letterParentId', DRE__Value__c='{!MUSW__Application2__c.Id}', DRE__DRE_Group__c=rgroupA.Id, DRE__DRE_Rule__c=r.Id);
        DRE__DRE_Result__c rgroupA_result3 = new DRE__DRE_Result__c(DRE__Attribute__c='letterOutputType', DRE__Value__c='Pdf', DRE__DRE_Group__c=rgroupA.Id, DRE__DRE_Rule__c=r.Id);
        insert new DRE__DRE_Result__c[]{rgroupA_result1, rgroupA_result2, rgroupA_result3};
        
        // create settings
        DRE__DRESettings__c s = new DRE__DRESettings__c();
        insert s;
        DRE__DREObjectSettings__c ts = new DRE__DREObjectSettings__c(Name='MUSW__Application2__c', DRE__Trigger_Enabled__c=true);
        insert ts;
        
        // trigger DRE
        Test.startTest();
        update p;
        Test.stopTest();
        
        SObject[] blr = Database.query('SELECT Id from BGBL__Batch_Letter_Job__c');
        System.assertEquals(1, blr.size(), blr);
    }
}